### ISSUE TITLE
Mobile: When selecting labour, user labour hours should be always available

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#1]
See screen below... labour quote hours should be read and write, always blank so user can enter value. User is allowed to enter ZERO. Right now the quote hours is read only for records that have default labour hours

![image](https://cloud.githubusercontent.com/assets/5666297/11847932/c4e33dd8-a3ed-11e5-8fb9-e01c17a10147.png)

**Comment by d3sqa** [comment]
The Labour Hours is now editable. It will always be blank unless the user enters a value in this field. Zero is now allowed and save against a particular labour line.
Fixed in development environment. It will be available in the next release at UAT

**Comment by giovanicani** [comment]
Will test once available on UAT

**Comment by giovanicani** [comment]
works. closing.
