### ISSUE TITLE
Cloud: Labour VMRS Field Missing info

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#10]
Rename VMRS labour to Sys-Asy (which means system / assembly).

Make the column wider, make sure the 7 digits are shown (999-999).

![image](https://cloud.githubusercontent.com/assets/5666297/11850174/b50b4a84-a3f9-11e5-98d4-71d855b16d01.png)

**Comment by d3sqa** [comment]
The column header is renamed to Sys-Asy. 7 characters are allowed including the hyphen '-'.

However, there is one exception regarding a system 'VisaSC' which makes it 6 characters before hyphen. Can you please suggest the work around for this ? Can we leave it as it is ?

![image](https://cloud.githubusercontent.com/assets/13255706/11925838/33b23be6-a7e1-11e5-8ddc-5057cff842d4.png)

**Comment by giovanicani** [comment]
Leave as is. This vmrs code will be deleted in the coming months. Thanks. 

--
Giovani Cani

**Comment by giovanicani** [comment]
done.
