### ISSUE TITLE
Mobile: Request for barcode or picture when resuming a MRO with status equals ASSIGN

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#100]
The first time that a mechanic will work on a MRO created from Quote, the status is **ASSIGNED**.

When the user clicks on RESUME, there should be a popup for user to:
- read barcode, 
- button barcode not found (enter license plate and preferred number - take pictures) 
- override

![image](https://cloud.githubusercontent.com/assets/5666297/12594055/25a0ffba-c442-11e5-84b0-55ae00c6bf4f.png)

After resume is pressed request BC or unit LP and TR#

![image](https://cloud.githubusercontent.com/assets/5666297/12594035/10cab630-c442-11e5-8253-e5db40cd73b0.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
Giovani to test.

**Comment by giovanicani** [comment]
works. thanks!
