### ISSUE TITLE
Cloud: Incorrect Image description

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#101]
***Picture was take from mobile***, description should be the same as labour line (there is no place on the mobile to change image description), when photo is taken from Mobile. It is not happening, screen screen shot below.

![image](https://cloud.githubusercontent.com/assets/5666297/12620029/96d8745a-c4e8-11e5-8b3f-3ca58dfe9f36.png)

 In summary, the description: **QOUTE LABOUR DAMAGE NOTES** should not be there. It should have been: 
![image](https://cloud.githubusercontent.com/assets/5666297/12620091/d57b2612-c4e8-11e5-95d8-969f1357adc5.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The Labour Line description will now reflect at the image pop up window when the labour is added from mobile. Please validate after getting latest application updates (UAT)

![new12222222222](https://cloud.githubusercontent.com/assets/13255706/12637913/cc11dbac-c5ba-11e5-91cb-989fc1559d9a.png)

**Comment by giovanicani** [comment]
okay, Giovani to test.

**Comment by giovanicani** [comment]
works thanks
