### ISSUE TITLE
Cloud: Add Edit Image Description button

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#103]
See image below:

![image](https://cloud.githubusercontent.com/assets/5666297/12620772/975b7a78-c4eb-11e5-9605-fb534c086158.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3ssupport** [comment]
Edit image description is done. Only space issue remaining in editing so working on it.

**Comment by d3sqa** [comment]
Space is now allowed while editing image description. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works, thanks!
