### ISSUE TITLE
Cloud: Create Quote from RTMI, please make the button readily available once Inbound is Approved.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#105]
Right now user has to approve, refresh screen for the button to show up.

Discussed this with the team over Skype.

![screen shot 2016-01-27 at 11 04 55 am](https://cloud.githubusercontent.com/assets/5666297/12624051/fd3a1548-c4fa-11e5-8cc4-2ae76eb944ea.png)

**Comment by d3sqa** [comment]
The button will now be available as soon as the user approves an inbound RTMI. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
okay.
