### ISSUE TITLE
Mobile: MRO Check List issue, if labour line associated to CL is deleted

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#106]
Mechanic Danny Camara showed me that in MRO, if he add a labour (eg, PM-A) which requires a checklist. Then he deletes that labour. And then he try to complete the MRO, the program will still ask him to complete the checklist.

Although this is not directly related to Quote, please fix, as we are deploying a new version of the MRO / Quote application in the coming weeks. 

Thanks!

**Comment by d3sqa** [comment]
Done. When a checklist associated labour is deleted, the application will not ask the user to complete the checklist.
The fix is available via application updates at UAT

**Comment by giovanicani** [comment]
Works!
