### ISSUE TITLE
Cloud: When uploading, image description adding part description - incorrect

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#107]
See attached, it should only show miscellaneous, and not the parts description.

![screen shot 2016-02-01 at 8 00 34 am](https://cloud.githubusercontent.com/assets/5666297/12718129/5c2ec6bc-c8ba-11e5-8131-f5a4b27b5712.png)

**Comment by giovanicani** [comment]
Also, description should appear on quote report, it is not showing. It should show on top of the image.

**Comment by d3sqa** [comment]
Description issue is fixed now. The description also reflects on the report on top of the image. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
done, thanks!
