### ISSUE TITLE
Cloud: Sorting adjustment

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#108]
Please sort the list below by In Date desc. Thanks!

![image](https://cloud.githubusercontent.com/assets/5666297/12719248/ea23c0d8-c8c1-11e5-8a9f-9469d505ffce.png)

**Comment by d3sqa** [comment]
The In Date is sorted in descending. Please see below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/12741605/c2820308-c99f-11e5-8a9e-70c1659bdc2c.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
done, thanks!
