### ISSUE TITLE
Cloud: Verbiage Tweak

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#109]
Please change on the Quote Detail screen...

"Estimate Hours" to "Mech. Estimated Hrs."
"Quote Hours" to "Cust. Quoted Hrs."

![image](https://cloud.githubusercontent.com/assets/5666297/12719127/3667b52c-c8c1-11e5-8430-9923f71bbd66.png)

![screen shot 2016-02-01 at 9 14 37 am](https://cloud.githubusercontent.com/assets/5666297/12719616/3e90f756-c8c4-11e5-95a6-40f719efd4c8.png)

**Comment by d3sqa** [comment]
Verbiage has been changed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12741844/f1d2dee6-c9a1-11e5-99f0-e514989841b4.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
done, thanks!
