### ISSUE TITLE
Cloud: Labour Image description is not the one entered when image was uploaded

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#11]
Above Image #1, should have been the note entered when uploading the image.

![image](https://cloud.githubusercontent.com/assets/5666297/11850467/6bfb2d4e-a3fb-11e5-8f3f-69ee334e1ffe.png)

**Comment by giovanicani** [comment]
please fix this one...

**Comment by d3sqa** [comment]
Fixed. Done at Development Environment. It will be available in the next release at UAT.

**Comment by giovanicani** [comment]
Works well on the report, but on the popup there is no description...

Please add the Image # and description entered when uploading the image.

![image](https://cloud.githubusercontent.com/assets/5666297/12041206/3991daa0-ae3d-11e5-94f4-8b9c6bce1947.png)

**Comment by giovanicani** [comment]
fixed.
