### ISSUE TITLE
Cloud UAT: Email send not working

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#110]
See image below... email with invalid address not working. It keeps spinning forever.

![image](https://cloud.githubusercontent.com/assets/5666297/12721486/12c0a572-c8ce-11e5-910d-df329474364e.png)

**Comment by d3sqa** [comment]
The validation on invalid email address format has been applied. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works! thanks!
