### ISSUE TITLE
Cloud: Make default records on audit log 50

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#111]
Please make it 50 as default. available values should be 25 / 50 / 100 as per standard discussed earlier.

**PLEASE ALSO CHANGE WORK ORDER AUDIT LOG** Thanks!

![image](https://cloud.githubusercontent.com/assets/5666297/12723466/9ba2149e-c8d7-11e5-824f-e954d14d00a1.png)

**Comment by d3sqa** [comment]
By default, 50 records will be displayed at the audit log grid

![image](https://cloud.githubusercontent.com/assets/13255706/12740316/c8ea1624-c993-11e5-961c-49d3e2f69977.png)

Available values will be 25, 50 and 100 as written in the ticket. But as per the discussion on standard, the values are 25, 50 and 500

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
done, thanks!
