### ISSUE TITLE
Cloud: Small tweak on the history column width 

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#112]
as discussed during the meeting, please make the columns proportional to the content of the column.

**Comment by d3sqa** [comment]
Please check the column size adjustment now

![image](https://cloud.githubusercontent.com/assets/13255706/12773113/2770c122-ca5a-11e5-8dfe-db076834089d.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
thanks!
