### ISSUE TITLE
Cloud: Center age column, header and content

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#113]
Dashboard and Quote listing.

![image](https://cloud.githubusercontent.com/assets/5666297/12764182/4896c80e-c9c6-11e5-80b9-4f0a39ea0be4.png)

**Comment by d3sqa** [comment]
Column header and data is now centrally aligned at Quote Listing and Quote dashboard. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12775308/c2bb3888-ca6e-11e5-8f90-3d798c6958dc.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
verified, thanks!
