### ISSUE TITLE
Cloud: Permission for Quote Approval (Trailer / Reefer)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#114]
Similarly to the ALLOW_CLOSE_QUOTE, please add one for approving quotes as well:

ALLOW_APPROVE_TRAILER_QUOTE
ALLOW_APPROVE_REEFER_QUOTE

Please add on production and UAT script to give access to Jon Drohan and John Dejong.

**Comment by d3ssupport** [comment]
Done in development. after QA test will move to UAT.

**Comment by d3sqa** [comment]
Done and ready for testing in UAT Environment

**Comment by giovanicani** [comment]
works, however found a bug when a user that is not allowed to approve, 

checks and unchecks the Reefer check box at the top. When this happens the approval at the bottom becomes available to be approved.

**Comment by d3sqa** [comment]
@giovanicani, the functionality is working fine. For the sake of testing we have given reefer approval rights to 4-master which could have resulted in the above issue.
Can you please retest and give your feedback ?

**Comment by giovanicani** [comment]
issue resolved.
