### ISSUE TITLE
Cloud: PO # needs to be entered, if Customer Requires PO before an RO is created from Quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#116]
If PO # is blank and Customer Requires PO... when user clicks "Create ROs from Quote", do not allow, and show message.

This customer requires PO, RO cannot be created.

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
great thanks!
