### ISSUE TITLE
Mobile: When entering labour from Mobile, Quoted hours should be null

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#117]
When entering labour from mobile, quoted hours should be null.
![image](https://cloud.githubusercontent.com/assets/5666297/12764425/ab2767ca-c9c7-11e5-8960-fe34427ae8a0.png)

When user clicks one of the 2 options below....
![image](https://cloud.githubusercontent.com/assets/5666297/12764448/c7e981c2-c9c7-11e5-9e9a-7899e9a94df5.png)

..., if quoted hours are null, then stop approval and warn user: 
"There are parts without Quoted quantity and/or Charge $"

... similar validation in case quantity or parts charge are not informed.
"There are labour lines without Quoted Hours and/or Charge $"

**Comment by d3sqa** [comment]
Quote Hours are now NULL from mobile and reflects no value at 'Cust. Quoted Hrs' column at cloud. Done. Mobile application updates are available at UAT

Work in progress on 2nd part of the ticket

**Comment by d3ssupport** [comment]
Done in Development!

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment

![new1111111111](https://cloud.githubusercontent.com/assets/13255706/12811713/0e86ee7e-cb50-11e5-809a-bde88adc3362.png)

**Comment by giovanicani** [comment]
change verbiage from:  

don't have any parts 

to:

doesn't have any parts.

Will test the rest.

**Comment by giovanicani** [comment]
works. just please do the verbiage change and we should be good to go.

**Comment by d3sqa** [comment]
In case of multiple labour line, Please see screenshot below (Used don't):

![image](https://cloud.githubusercontent.com/assets/13255706/12838555/4c279a70-cbf1-11e5-92e7-2cf4e26c30c6.png)

In case on one labour line (Used doesn't):

![image](https://cloud.githubusercontent.com/assets/13255706/12838615/0f47ff5e-cbf2-11e5-96ea-6138896a3aac.png)
