### ISSUE TITLE
Cloud / Mobile: Please add Shift code on labour selection

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#118]
Please add shift on Quote Labour selection, Cloud and Mobile, mandatory field like reason.

When creating MRO, copy the shift into MRO Labour Line.

Make this change on Mobile and Cloud versions of the Quote.

![image](https://cloud.githubusercontent.com/assets/5666297/12764673/20da346a-c9c9-11e5-8f0d-815d3a9e3798.png)

**Comment by d3sqa** [comment]
Done from mobile. Application updates are available at UAT
Work in progress at cloud

**Comment by d3sqa** [comment]
Done at cloud end also. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
done. thanks!
