### ISSUE TITLE
Cloud: Dashboard sorting

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#119]
Please make it so that oldest Quotes are on top... Higher ages on top.

![image](https://cloud.githubusercontent.com/assets/5666297/12770541/455243f2-c9ef-11e5-8aca-781924b2f09d.png)

**Comment by d3sqa** [comment]
On the Quote Dashboard, sorting based on Age (Days) has been done. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12773342/8b2157de-ca5c-11e5-885f-5a6ff537765c.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
great thanks!
