### ISSUE TITLE
Cloud: Quote from RTMI - Show quote number on the popup

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#12]
On the message below:

![image](https://cloud.githubusercontent.com/assets/5666297/11850584/3139bb8e-a3fc-11e5-9a42-be63b30f675c.png)

Show Quote #, example "Quote Q123322 already created for this RTMI"

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Quote # is now displayed at the message box prompted when a Quote already exists against the RTMI. Done at development environment.
The fix will be available at UAT when next release is deployed there

![image](https://cloud.githubusercontent.com/assets/13255706/11869125/ba7e585e-a4de-11e5-81e7-e46d7be4a8f1.png)

**Comment by giovanicani** [comment]
looks good thanks.
