### ISSUE TITLE
Cloud: Remove status overdue

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#120]
Remove status below:

![image](https://cloud.githubusercontent.com/assets/5666297/12770571/77874bec-c9ef-11e5-9d71-b44531728b95.png)

If overdue show on the "customer approval pending" section but with red background on the Quote number cell.

On the Quote detail screen also, if overdue, show Quote field with red back ground if overdue. Customer Approval Pending - Overdue, should no longer exist.

**Comment by d3sqa** [comment]
Status, Customer Approval Pending - Overdue has been removed from quote dashboard. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12774391/2c19f89a-ca66-11e5-89a9-d65a9353f2ad.png)

The background for overdue quotes will be red within the 'Cust. Apprvl Pending' status. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12774387/22333936-ca66-11e5-87ce-b00b5607ad3a.png)

At the Quote Detail screen, the Quote # will be red. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12774420/80eca4da-ca66-11e5-9541-9611b4e12abf.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
great thanks!
