### ISSUE TITLE
Mobile: MRO Auto Hold, confusing wording. Please change verbiage as per below

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#121]
Hi, on MRO, the word below : Auto Hold is very confusing to users.

Can we do it so that instead of 2 lines, we have one line for each Auto Hold... and change the verbiage on the audit log to: 

"MRO has been auto saved on the server due to tablet being idle for an extended period of time"

![image](https://cloud.githubusercontent.com/assets/5666297/12770706/abe2300e-c9f0-11e5-8431-cb701c3131ad.png)

**Comment by d3sqa** [comment]
Verbiage for auto hold has been changed. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12773954/6ca05e26-ca62-11e5-84b0-bdcd1cc779cd.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
great thanks!
