### ISSUE TITLE
Cloud: Add self assign button on quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#123]
See image below for details

![image](https://cloud.githubusercontent.com/assets/5666297/12786837/d5011c5a-ca60-11e5-9aa4-aef389182cea.png)

**Comment by d3sqa** [comment]
Tool tip and button provided. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12808853/f2fa9ba6-cb3b-11e5-9a56-3b044968a788.png)

Functionality has been done. By clicking 'Self' button, the logged in user will be populated in the Assigned To drop down. The user then needs to click the Save button to save the data. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works thanks!
