### ISSUE TITLE
Cloud: When creating Quote from RTMI, Assigned To should be blank

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#124]
Assigned to field should be blank when creating QUOTE from RTMI.

Similarly to the Trailer / Reefer checkbox, when saving quote, if assigned to is blank user needs to enter it, or click on the new button "SELF", indicated on ticket #123

**Comment by d3sqa** [comment]
The Assigned To will be blank whenever quote is created from RTMI. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
okay!
