### ISSUE TITLE
Cloud / Mobile: Parts without a group list issue

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#125]
Please make sure that all ACTIVE parts are shown on the parts selection for Quote Cloud and Mobile.

Parts that do not have groups associated should be shown also. I believe right now they are not.

Example: Part Code: ESTIMATEPART

**Comment by d3sqa** [comment]
Parts without groups will be displayed at the parts grid at cloud. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12810676/7da8432c-cb49-11e5-8de3-3f9a539879cf.png)

Please note that group information is not present at mobile end so no changes have been done there.
Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Estimate part is not available on mobile. Please check and update ticket.

**Comment by d3ssupport** [comment]
Done in mobile side as well. Please take full sync before test

**Comment by giovanicani** [comment]
works!
