### ISSUE TITLE
Cloud MRO: Grid Date does not match RO Detail Date

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#126]
See screen shot below. Most likely a TZ issue.

![image](https://cloud.githubusercontent.com/assets/5666297/12793332/127563b2-ca7e-11e5-99e4-80a11ea325f5.png)

**Comment by d3sqa** [comment]
Dates will now remain same at RO details and RO Listing. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
resolved.
