### ISSUE TITLE
Cloud: Quote Status adjustment

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#127]
Please make it so that if a Quote is approved and no MRO has been created, or they have been created but not completed, please make the status = **WAITING MRO(s) TO BE COMPLETED**. 

This status should have a blue background and on the dashboard, located just after Customer Approval Pending.

Examples:

![image](https://cloud.githubusercontent.com/assets/5666297/12826354/b2e40a68-cb48-11e5-9e8b-017976fa3b43.png)

![image](https://cloud.githubusercontent.com/assets/5666297/12826344/9f096308-cb48-11e5-9937-b149883133ab.png)

![image](https://cloud.githubusercontent.com/assets/5666297/12825258/746943fc-cb43-11e5-816f-89b975a764ae.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done and ready to test in UAT Environment

**Comment by giovanicani** [comment]
Not working, 2 ROs are Completed, but still with status saying that is waiting to be completed, see below.

![image](https://cloud.githubusercontent.com/assets/5666297/12924302/611ce5be-cf27-11e5-902c-e5330dcc63d9.png)

**Comment by d3sqa** [comment]
The status will now be changed without clicking save button. Please see screenshots below:

1. When one RO is EMDECS OK and one is in ASSIGNED status. The status will be WAITING MRO(s) TO BE COMPLETED.

![image](https://cloud.githubusercontent.com/assets/13255706/12943161/2af68e60-d001-11e5-9555-393a25cdbf0e.png)

2. When both ROs are in EMDECS OK. Simple refresh the page to get the status MRO REVIEW AGAINST QUOTE PENDING

![image](https://cloud.githubusercontent.com/assets/13255706/12943273/016815d6-d002-11e5-9fdb-56bb35c2cfd9.png)

Latest updates are available at UAT

**Comment by giovanicani** [comment]
thanks.

**Comment by giovanicani** [comment]
working!
