### ISSUE TITLE
Mobile: Overriding email on the cloud

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#129]
Every time a Quote is resumed on the Mobile it overrides the email address entered on web.

See quote 330, delete all emails on cloud, enter an email, for instance: gcani@trailcon.com.

Sent to mobile, after saving, all emails are back and gcani@trailcon.com is gone.

**Mobile should only prepopulate emails, if Quote is created on Mobile.** After created never override.

**Comment by d3sqa** [comment]
Emails won't be changed now. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works.
