### ISSUE TITLE
Cloud: Void does not work.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#13]
When a previous quote is voided, user can create a new quote from the same RTMI.

**Comment by d3sqa** [comment]
If the previous quote is voided, the user can now create a new quote against the same RTMI. Done at development environment. The fix will be available at UAT when new release is deployed there

**Comment by giovanicani** [comment]
When voided or status is CLOSED. No update on the QUOTE is allowed.

All fields should be locked down.

**Comment by d3sqa** [comment]
Done. Fixed at Development Enviroment. It will be available in the next release at UAT

**Comment by giovanicani** [comment]
works. thanks.
