### ISSUE TITLE
Cloud: If part Charge is ZERO or NULL please show ERROR

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#131]
When internally approving (Trailer or Reefer) If part charge is ZERO or NULL show ERROR indicating that they have to be entered, cannot be null.

Similar to labour.

**Comment by d3sqa** [comment]
Following message will be prompted whenever Charge $ is left blank or with a zero

![image](https://cloud.githubusercontent.com/assets/13255706/12838960/e229f4e2-cbf5-11e5-86cf-3c3923292dec.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Not working for parts, was just able to approve with a ZERO dollar part.

**Comment by giovanicani** [comment]
working!
