### ISSUE TITLE
API EMDECS: Limit labour line to 50 chars when sending to EMDECS

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#132]
As discussed via mail, limit labour line to first 50 chars when sending to EMDECS to avoid error.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Limit is applied on labour line to be 50 chars while sending to EMDECS. Fix has been deployed at production environment

**Comment by giovanicani** [comment]
works.
