### ISSUE TITLE
MRO: Add link on MRO History

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#133]
Like it was done on Quote, please add link to history for the following records:

RTMI
Quote
MRO

Service Call and Book Off Board wont have a link since they are still running in TCS.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Link for the records has been provided. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12878446/df5c1684-ce46-11e5-96f2-8e173541d5cc.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
good thanks!
