### ISSUE TITLE
MRO: Add branch filter on Apply Filter Box

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#134]
Add branch filter, add filter before the RO # field.

To filter please use the loc_id on the ym_users associated to the use_id_assigned_to on the rep_work_orders fields.

** Show all by default **

![image](https://cloud.githubusercontent.com/assets/5666297/12876205/7525e122-cdca-11e5-8f24-6d7822ef1b2e.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Branch field has been added to the MRO filter. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12883475/1b844216-ce7a-11e5-9ed4-49962070b17c.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works thanks!
