### ISSUE TITLE
MRO: Trailer History, remove license plate requirement

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#136]
On the MRO mobile trailer history screen, remove the license plate field.

If user enter the trailer number and there are more than one trailer number with the same number, show popup so that user can select the correct trailer number.

**The same feature that was done the on the quote when creating quote and entering a trailer number that has more than one ACTIVE number on the database. Use same box and columns.**

**Comment by d3sqa** [comment]
License plate has been removed from Trailer History screen. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12884033/641ad230-ce7d-11e5-80fd-27e4c7da60f0.png)

Pop up is now available. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12884045/7114fd3a-ce7d-11e5-8012-0afba1afe4f7.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
UAT OK!
