### ISSUE TITLE
Cloud: Void Quotes should not appear on the dashboard

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#137]
Voided quotes should not appear on DASHBOARD.

**Please do not show voided quotes on dashboard tab**

![image](https://cloud.githubusercontent.com/assets/5666297/12891330/65abe008-ce55-11e5-9d00-eccb488943eb.png)

**Comment by d3sqa** [comment]
Voided quotes will not be displayed at the Quote's dashboard. Fix deployed at production

**Comment by giovanicani** [comment]
good thanks!
