### ISSUE TITLE
Cloud: PO # Entered but system still asking for PO # before creating MRO

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#138]
Looks like the system is going to the database to show PO validation.

Please make sure that the screen is saved so that the PO number entered on the client side is considered once creating an MRO.

Also make sure that after saving the user does not loose focus of the screen where they were. Saving should be transparent for user.

Another option would be checking screen instead of DB to show validation, but I would rather save all info to keep it consistent and then do the check.

**Comment by d3sqa** [comment]
The PO# will be saved as soon as the focus shifts from the PO# field. The saving is now transparent. Ready to be deployed at Prod.
Fix available at UAT

**Comment by giovanicani** [comment]
works thanks!
