### ISSUE TITLE
Mobile: MRO add PM info on the mobile app.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#139]
Giovani to add more details to this task.

**Comment by giovanicani** [comment]
Using query provided on ticket: #28 please add the PM Read Only on the tablet side.

![image](https://cloud.githubusercontent.com/assets/5666297/13011566/5d4b3788-d175-11e5-99f2-81e7f4715146.png)

![image](https://cloud.githubusercontent.com/assets/5666297/13012041/91751b30-d177-11e5-8fc7-ea8e7b38741a.png)

When overdue, show in red.

Try to make the request to server when PM Schedule button is pressed. **The mobile should only be a text field, keep the query on the server so that if we need to tweak we wont need to release to all mobiles a new version. Mobile should only receive a formated STRING**

**Comment by giovanicani** [comment]
make it big letters as on the mockup screen.

**Comment by d3ssupport** [comment]
Work in progress

**Comment by d3sqa** [comment]
Button has been added. Please see below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/13068421/0e7ac148-d49d-11e5-843e-569d967b1f81.png)

Functionality has been done. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13068434/21877330-d49d-11e5-83b1-346e516e8798.png)

The change has been incorporated in development. It will be available in the upcoming UAT debug

**Comment by giovanicani** [comment]
Change message below to: "PM Information not available for this unit."
![image](https://cloud.githubusercontent.com/assets/5666297/13205814/b844b5b0-d8be-11e5-8383-31fa28ec8fe6.png)

**Comment by d3sqa** [comment]
Work in progress on message revision

Latest PM information has been retrieved from the server every time the PM schedule button has been clicked

**Comment by giovanicani** [comment]
As per Tufail, it is done already, coming on the next release.

**Comment by d3ssupport** [comment]
Done in UAT. Ready for Testing!

**Comment by giovanicani** [comment]
works, thanks!
