### ISSUE TITLE
Mobile: Quote coming back from mobile with Zero Quantity

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#140]
Quote created on cloud, sent to mobile for pictures on labour, when came back to cloud all part quantities were ZERO.

Please fix this ASAP.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Part quantity value will be retained when quote is resumed and closed from mobile. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works now.
