### ISSUE TITLE
Report: Header of the Report is blank

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#141]
See picture below, all the branch information is missing.

![image](https://cloud.githubusercontent.com/assets/5666297/12899868/666dad2e-ce81-11e5-854e-e3a01d46c8f9.png)

**Comment by giovanicani** [comment]
all the address is on the rla_locations table.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done and deployed at production. Branch information is now displayed at the header of the report

**Comment by giovanicani** [comment]
good thanks!
