### ISSUE TITLE
Cloud: Dashboard add 2 columns to indicate reefer / trailer quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#142]
After Quote # add 2 columns labour "Tlr" and "Rfr"

If Reefer Quote then check Rfr
If Trailer Quote then check Tlr
If Reefer and Trailer Quote then check Rfr and Tlr columns.

This will allow users to know type of quote on the dashboard.

**Comment by d3sqa** [comment]
New columns has been added. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12912781/9d544e22-cf3c-11e5-99ec-5486e0025e68.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
looks good. thanks!
