### ISSUE TITLE
Cloud: Emails not populating email box

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#143]
On cloud, do the following:

1. Create Quote
2. Enter email address on the header
3. Enter labour and parts
4. Approve Trailer
5. Send to customer, Yes, when popup box appear TO emails are blank, they should be the emails entered on the header. Same thing happens when clicking on "Quote / Email Report" button.

Need this to be fixed ASAP.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
@giovanicani, we have tried to replicate this issue at prod with test barcode T007171, followed the above written steps, but unable to replicate it. The email address populated at both email pop up windows (directly from the button and at send to customer).

![image](https://cloud.githubusercontent.com/assets/13255706/12913293/a46ff406-cf3f-11e5-9085-90f253d2a028.png)

Can you please recheck and let us know ?

**Comment by giovanicani** [comment]
See screen shot...

Steps:
1. Created Quote from cloud
2. Entered labour / parts
3. Entered email address: gcani@trailcon.com
4. Press email button... address is blank as seen below
![image](https://cloud.githubusercontent.com/assets/5666297/12920639/66111938-cf17-11e5-908c-573fdbb17484.png)

If I save before clicking on email, it seems to work. Is there a way to save quote as soon as button is clicked to make sure all is saved before the report runs ?

**Comment by d3sqa** [comment]
The email address will now be saved at the Update Quote form as soon as the user enters data into email field and focus out of the field. The email address will be saved.
If the entered email address already exists in the list, it won't be displayed in the TO field. However, if a new email address is saved, it will be displayed in the TO field.
Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works.
