### ISSUE TITLE
Database: Rep_Work_Order_Qt_Status_WF not consistent DDL

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#148]
Why this table doesn't have the AUDIT fields in the correct sequence ???

Why CREATE_USER is the first field ?? Why you are not using the audit fields template I gave you.

Shouldn't the create_user be using the context variable like the other tables ??

**Comment by d3sqa** [comment]
The table sequence is correct. The create user sequence was wrong in the view which is now corrected. Also in the audit trigger, the context variable has been corrected

**Comment by giovanicani** [comment]
thanks!

**Comment by giovanicani** [comment]
Can you please change NOTES from CLOB to VARCHAR2(1000), there is no need to have a CLOB field here.

Also, next time please add the word "_flag" after any flag field... is_checked should be is_checked_flag.

**Comment by d3ssupport** [comment]
DDL Issue fixed. Ready for Test in UAT.
