### ISSUE TITLE
Cloud: Add validation when user clicks create MRO from Quote Button

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#149]
If trailer does not have a license plate and does not have a barcode, ** Do not allow user to create MRO from Quote **.

Show ERROR message: 
**Trailer does not have a barcode or license plate - MRO cannot be created. Please update the trailer license plate or assign a barcode before creating MRO(s). [OK]**

**Comment by giovanicani** [comment]
LP and Trailer # are critical and need to be informed before creating MROs

**Comment by giovanicani** [comment]
ADjustment comment to include barcode scenario. Thanks!

**Comment by d3sqa** [comment]
The error message will be displayed when both the barcode and license plate are NULL. However, if either of them is present, the message will not be prompted. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12941370/78c98d9e-cff3-11e5-9bda-54affa0cb50f.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
okay thanks!
