### ISSUE TITLE
Cloud: Quote List - Increase Customer column length

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#15]
... reduce Age (days) column 

![image](https://cloud.githubusercontent.com/assets/5666297/11850881/e8b91fec-a3fd-11e5-8827-01c935253b26.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Customer Column at the Quote Listing has been done and is available at the development environment. The fix will be available at the UAT in the upcoming release

![image](https://cloud.githubusercontent.com/assets/13255706/11868658/4427bb30-a4db-11e5-8367-5c1b3fb6c0e4.png)

**Comment by giovanicani** [comment]
looks good. thanks.
