### ISSUE TITLE
Cloud: Bug - When updating labour, sys-asy not changing.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#151]
Following steps to replicate:

1. Add Labour 1 (01-000 - GET UNIT MOVED)
2. Double click on labour 1, at the top, search for: INSTALL DOOR SAVER (07-000)
3. Enter Cust. Quoted Hours: 5.00
4. Press UPDATE
5. Grid shows description correct, but SYS-ASY is still 01-000 <<<<-- BUG, this needs to be fixed as can cause inconsistencies.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Fixed at both create quote and update forms. The SYS-ASY will now be updated accordingly. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
OK works!
