### ISSUE TITLE
Mobile: MRO BC Issue when unit is brand new and doesn't have a license plate.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#152]
When unit is brand new, has a BC but not a license plate... user get stuck on the verification screen.

To test this, go to ym_units, remove license plate (make it null), make sure there is a BC, commit.

Now try to create a MRO on the tablet for that unit, you will see the problem. If BC is available we should bypass the license plate requirement.

Will this cause problem somewhere else ?

**Comment by d3sqa** [comment]
Done and ready to test in UAT. Latest application updates are now available at UAT

**Comment by giovanicani** [comment]
works!
