### ISSUE TITLE
Cloud: User is allowed to change STD hours, bug

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#154]
To replicate follow the steps:

1. Add labour with std hours
2. REfresh quote 
3. Edit labour added on 1, you will see that the estimated hours is open to be edited, and should not be.

![screen shot 2016-02-10 at 3 34 28 pm](https://cloud.githubusercontent.com/assets/5666297/12960998/3a79e976-d00c-11e5-9b01-3803d879114a.png)

**Comment by giovanicani** [comment]
this was found when testing #153

**Comment by tufailzafar** [comment]
work in progress

**Comment by d3sqa** [comment]
Done. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works!
