### ISSUE TITLE
Cloud: Quote just created, why there is an RO associated to quote ??? very frustrating 

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#155]
![screen shot 2016-02-10 at 3 55 23 pm](https://cloud.githubusercontent.com/assets/5666297/12961502/c939fc4e-d00e-11e5-917d-74e042c6263a.png)

**Comment by d3sqa** [comment]
It is happening because the ROs are fetched based on the Unit i.e. whenever Quote is created against a unit which has 2 ROs associated, they will be populated in the RO and Status Grid

We are working on it to associate it directly with quote rather than a unit

**Comment by d3sqa** [comment]
Issue has been fixed. RO(s) are now displayed against a quote. Ready to test in UAT

**Comment by giovanicani** [comment]
looks ok now.
