### ISSUE TITLE
Mobile: MRO - Indicator that part was added via barcode / camera

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#156]
Please add a new flag on the rep work order parts and WV view called: part_added_barcode_flag, VARCHAR2(1), values Y and N, NOT NULL, DEFAULT N.

If part was added via the barcode button, please make it Y.

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by d3sqa** [comment]
New column has been to the REP_WORK_ORDER_PARTS table. Whenever barcode is added via a camera, the value stored against this column will be Y else N.

![image](https://cloud.githubusercontent.com/assets/13255706/13068582/94542bc8-d49e-11e5-9e17-0e53ea0a5379.png)

Change has been incorporated at development and will be available at UAT in the upcoming debug

**Comment by giovanicani** [comment]
works, thanks!
