### ISSUE TITLE
Rep_Work_Order_Quotation_Wv, why do we have barcode and others in this table?

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#157]
Why do we have these 4 fields in the table / view ?

Barcode, license plate, unit number and preferred should all be coming from ym_units. No need to drop the fields as they may be useful in the future, but make sure that all quote programs use the ym_units to retrieve and validate this info.

![image](https://cloud.githubusercontent.com/assets/5666297/13205583/48563454-d8b9-11e5-94be-ec84b868f554.png)

**Comment by giovanicani** [comment]
This message should not be showing, as ym_units has the correct license plate... this is related to the item above...

![image](https://cloud.githubusercontent.com/assets/5666297/13205667/3880e342-d8bb-11e5-850f-b8712d472262.png)

**Comment by d3ssupport** [comment]
We are retrieving data from ym_units_wv. we are not bringing all units locally that why are using these fields  for open Quote's and  inquiry screen.

**Comment by giovanicani** [comment]
Team to review impact to retrieve barcode, unit number and preferred number from ym_units. Mobile can still use the temp fields highlighted above.

Retrieving from ym_units will allow users always seen the latest info on the units from the quote screen.

Team to assess impact and update ticket.

**Comment by d3sqa** [comment]
At Quote Listing and Quote detail form, we are now retrieving data from YM_UNITS. There is no impact on functionality

**Comment by giovanicani** [comment]
thanks!
