### ISSUE TITLE
Mobile: Safety (PM-S) incorrect date on verification screen 

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#159]
Where is the last safety coming from on the MRO / Quote Verification screen ?

It is not matching the database, please see screen shot below taken from **PROD**.

![image](https://cloud.githubusercontent.com/assets/5666297/13224212/7738a8b4-d955-11e5-85d6-dcd6d7faa6b4.png)

**Comment by d3sqa** [comment]
We are using the following table to retrieve the Safety data. Please see screenshot below:

![screenshot_6](https://cloud.githubusercontent.com/assets/13255706/13241701/5563ed88-da0f-11e5-8714-9cdd60b33120.png)

**Comment by giovanicani** [comment]
Ok. Leave as is then. 

--
Giovani Cani

**Comment by giovanicani** [comment]
issue has been resolved by Giovani. Did changes on the procedure that copies the data from EMDECS.
