### ISSUE TITLE
Cloud: Labour Image: Allow user to delete or mark as not available on customer report.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#16]
Make sure that:

Delete Button and Make Available on Customer Report are functional

![image](https://cloud.githubusercontent.com/assets/5666297/11851087/cbf0514a-a3fe-11e5-9918-c1fb04936749.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The image deletion feature at the image slider is now implemented. Just one tweak left i.e. when the image is deleted, the next image in line should be displayed without any delay

Only those images which are marked as available on report will be available on the report. Done at development environment. It will be available when the new release gets deployed at UAT

**Comment by giovanicani** [comment]
delete works well.

Just need to fix the allow image to show on the report. 

Images are still showing even when the check box is not marked.

**Comment by d3ssupport** [comment]
Fixed. Done at development Environment. It will be available when the new release gets updated at UAT.

**Comment by giovanicani** [comment]
works. thanks.
