### ISSUE TITLE
Quote Report: Space Improvement and add Disclaimer

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#160]
1. Improve Space between lines

![image](https://cloud.githubusercontent.com/assets/5666297/13398856/42735754-dece-11e5-82d5-68f66abb3e4c.png)

2. Please add disclaimer as per below a few lines below the total.

![image](https://cloud.githubusercontent.com/assets/5666297/13399056/58fefdba-decf-11e5-9642-4e35bc4287cd.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Space optimization has been done at Quote Report and is ready to test in UAT Environment.
Please see screenshot below:

![12344444444444](https://cloud.githubusercontent.com/assets/13255706/13424623/c3187204-dfc3-11e5-8f66-1f07cf205664.png)

**Comment by giovanicani** [comment]
Looking good! Thanks!
