### ISSUE TITLE
Mobile: Verbiage Change to keep consistent

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#161]
Please change "Location" label below to "Branch".

![image](https://cloud.githubusercontent.com/assets/5666297/13409351/a779aed2-df00-11e5-883b-997752727b56.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done at Quotes. Updates available at UAT

![image](https://cloud.githubusercontent.com/assets/13255706/13423716/6193b1d8-dfbe-11e5-8070-c777bad11ad7.png)

Is this needs to be done in MRO as well ?

**Comment by giovanicani** [comment]
No MRO. Just QUOTES.
