### ISSUE TITLE
Cloud: Users are getting Page Not Found when creating Quote from RTMI

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#162]
See image sent by user.

Work around is to reload page and press create quote again, then it works.

The page below happens after pressing create quote on the popup window. If you look for the logs in the server will most likely find what page it is trying to call. RTMI RTMI00027471 (after reloading page, it works). looks like the problem only happens right after approving the inbound.

![image](https://cloud.githubusercontent.com/assets/5666297/13505442/2ba865c0-e147-11e5-9eb7-10fe0633e005.png)

**Comment by d3sqa** [comment]
We are looking into it

**Comment by d3sqa** [comment]
Issue has been resolved. After approval, all the fields get disabled and masagr_id gets missing which is required to make the quote (This happens when the user directly creates a quote after approval).

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Is there a possibility to move only this fix into production ? Today or tomorrow ?

Thanks. 

--
Giovani Cani

**Comment by d3ssupport** [comment]
Yes. We can move tomorrow

**Comment by giovanicani** [comment]
Please do it tomorrow then. Thanks!

**Comment by d3sqa** [comment]
This fix has been propagated to production

**Comment by giovanicani** [comment]
Thanks. 

--
Giovani Cani

**Comment by giovanicani** [comment]
![screen shot 2016-03-07 at 2 08 47 pm](https://cloud.githubusercontent.com/assets/5666297/13580097/abac8272-e46e-11e5-9f59-2f11550ec7a2.png)

Getting this error on ALL Quotes being created from RTMI.

**Comment by giovanicani** [comment]
Tufail working on it.

**Comment by tufailzafar** [comment]
in UAT it is working but in production response is null, work in progress

**Comment by giovanicani** [comment]
resolved.
