### ISSUE TITLE
Cloud: When clicking on Quotes from DASHBOARD tab or LISTING tab please open a new tab

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#163]
Please open a new tab on the browser when user clicks to open a Quote, do the same thing for MRO, always open a new tab and do not override the current session.

This will be more user friendly and minimize performance impact

**Comment by giovanicani** [comment]
Tufail, can I please get an update on this one ? thanks

**Comment by d3sqa** [comment]
The MRO and Quote records can now be opened in a separate tab upon double clicking a specific record. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works thanks!
