### ISSUE TITLE
Cloud: Add RTMI column on Dashboard and Listing.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#164]
Add RTMI Column on dashboard as per below:

![image](https://cloud.githubusercontent.com/assets/5666297/13685131/00c78a16-e6dd-11e5-947f-68522a6a200e.png)

**Comment by giovanicani** [comment]
On Quote Listing, also add it after the quote #.

![image](https://cloud.githubusercontent.com/assets/5666297/13685572/0bc708fe-e6df-11e5-9d0d-92edb3dbb96d.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
RTMI # column has been added to the Quote Listing and Quote dashboard screen. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/13700048/4a2bb7ea-e7a0-11e5-88ea-d5446f90efd2.png)

![image](https://cloud.githubusercontent.com/assets/13255706/13700061/5ed94acc-e7a0-11e5-9efe-7d1c533f6bd5.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works thanks!
