### ISSUE TITLE
MRO: List Screen Main filter not working

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#166]
Please fix this for the release on saturday.

User should be able to search by all branches and mobile. And any other combination.

![image](https://cloud.githubusercontent.com/assets/5666297/13708266/9c40593e-e77b-11e5-816d-6f11b7c6b8f6.png)

**Comment by giovanicani** [comment]
When opening (or pressing refresh) the screen in UAT.
![image](https://cloud.githubusercontent.com/assets/5666297/13708389/5adf2686-e77c-11e5-96fd-6c5f0658bfc4.png)


When pressing search with no filter as per below... **Why are the results different if no filter is applied?**
![image](https://cloud.githubusercontent.com/assets/5666297/13708361/290e5d84-e77c-11e5-8bdb-995e959efebd.png)

**Comment by tufailzafar** [comment]
work in progress

**Comment by tufailzafar** [comment]
issue has been resolved and deployed into prod
Please be noted it is done through list query however; will be covered through store procedures as we discussed earlier

**Comment by giovanicani** [comment]
good thanks!
