### ISSUE TITLE
Mobile: Enable flash light (Quote and MRO)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#167]
Please have a toggle button on the picture taking screen to turn on and off the flash. Note that if the picture taking screen is closed, the flash should be shutdown to save energy.

![image](https://cloud.githubusercontent.com/assets/5666297/13731647/d9998484-e944-11e5-8b12-ac3be90a10d4.png)

Use the following parameters:

/ON to turn it on
/OFF to turn it off

If by any chance the EXE is not found, it should not trigger an error.

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide update on this activity.

**Comment by d3sqa** [comment]
Flash light feature has been done at MRO and the application debug has been placed at the tablet. Please test

Following are the screenshots:

![image](https://cloud.githubusercontent.com/assets/13255706/13877151/dd188422-ed2a-11e5-927d-3db75600ebd2.png)

**Comment by d3sqa** [comment]
Done at Quotes as well. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works! thanks!
