### ISSUE TITLE
Cloud: Search not working at ALL! Need it fix ASAP.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#169]
![image](https://cloud.githubusercontent.com/assets/5666297/13747209/90bef0ee-e9cd-11e5-9442-10fbceb0cec9.png)

**Comment by giovanicani** [comment]
Search seems to work, but now double clicking on the quote after searching does not open quote record.

![screen shot 2016-03-14 at 10 53 16 am](https://cloud.githubusercontent.com/assets/5666297/13748412/22307200-e9d3-11e5-88cd-
f41cd13a266a.png)

**Comment by d3ssupport** [comment]
Double click functionalty is working now. Issues has been fixed and verified.

**Comment by giovanicani** [comment]
fixed.
