### ISSUE TITLE
Cloud: Create ROs from Quote : Grid not working

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#17]
I just created a Quote from RTMI, see image below:

When I go to the Create ROs from Quote, there is a lot of ROs showing, not sure why. This should be blank.

![image](https://cloud.githubusercontent.com/assets/5666297/11851189/4fd87df2-a3ff-11e5-84f7-714f1d9f4911.png)

**Comment by d3sqa** [comment]
Validation has been applied now such that only those ROs will be displayed in the 'RO(s) & Status' grid which are created against the particular Quote #. Please check the below screenshot for reference:

![123](https://cloud.githubusercontent.com/assets/13255706/11863872/b21845a0-a4b9-11e5-8260-2fbb0d15d569.png)

**Comment by giovanicani** [comment]
Looks better. Thanks!
