### ISSUE TITLE
Cloud: Quote: unchecking customer approved, and pressing save does not SAVE!!!

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#170]
Why system is not saving when workflow flags are unchecked, need this to be fixed.

**Comment by giovanicani** [comment]
Works now as per Tufail, Anwar. QA to validate that all fields are being saved and update this ticket. 

Fix specific to the unchecking customer approved has been resolved and promoted to prod.

**Comment by d3sqa** [comment]
Fields have been verified. Unchecking flags feature has been also verified.

**Comment by giovanicani** [comment]
my assumption is that the issue has been resolved and moved into production.
