### ISSUE TITLE
Mobile: Several ROs with no picture and no license plate

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#171]
ROs should require license plate and picture when barcode is not available.

I am finding several ROs without license plate on the system, just a few examples:

R024358
R024361
R024256
...
etc...

**Comment by giovanicani** [comment]
License plate not being saved on all new ROs for this user, how is it possible that he was able to start the RO ?

![image](https://cloud.githubusercontent.com/assets/5666297/13758387/978b357c-e9ff-11e5-97f4-88f231f87dd3.png)

**Comment by giovanicani** [comment]
Use IDs of some users that reported the issue:

use_id: 95 -- Slavko
use_id: 107 -- rawle
use_id: 122 -- morris

**Comment by giovanicani** [comment]
![image](https://cloud.githubusercontent.com/assets/5666297/13758927/47260118-ea02-11e5-9e2d-826caa69326f.png)

**Comment by giovanicani** [comment]
Why License plate is blank over here as well?

![image](https://cloud.githubusercontent.com/assets/5666297/13759041/ca8cd766-ea02-11e5-84f1-dbd713df257e.png)

**Comment by giovanicani** [comment]
Placed on hold and now on the DB the license plate became NULL:

![image](https://cloud.githubusercontent.com/assets/5666297/13759108/27930764-ea03-11e5-82a3-ffb857945c3e.png)

**Comment by giovanicani** [comment]
Now after resuming and completing....
LP is blank.
![image](https://cloud.githubusercontent.com/assets/5666297/13759163/6364c71e-ea03-11e5-821b-4674b13b41ee.png)

And cannot complete after entered correct LP, system says, doesnt match:
![image](https://cloud.githubusercontent.com/assets/5666297/13759203/8796bf5c-ea03-11e5-8ab1-781eab34e5ba.png)

**Comment by giovanicani** [comment]
How does the mechanic close the MRO now ??

**Comment by giovanicani** [comment]
52 ROs had their license plate deleted today. This will cause issues on EMDECS and possibly billing.

**Comment by d3sqa** [comment]
The License Plate # issue has been resolved. 
The license plate numbers are now displayed at the RO detail form and inquiry screen. 
New application updates will be available soon

Discussion required on missing license plates issue for existing ROs

**Comment by giovanicani** [comment]
Validated, license plate is no longer being deleted. 

LP not showing on the screen is a visual fix only, does not affect the database and will be release in the next few days, pending Giovani's go ahead.

**Comment by giovanicani** [comment]
resolved. pending deployment.
