### ISSUE TITLE
Mobile: Remove / Hide Customer Name reference from the verification screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#172]
Remove / Hide Customer name as shown below.

![image](https://cloud.githubusercontent.com/assets/5666297/13760038/806530a2-ea07-11e5-8557-a7d073ce3c3a.png)

**On the RO detail screen, change the logic to the following (change cloud and mobile) :**

If Trailcon owned unit, auto populate with the customer of the last RTMI created that is RENTAL or LEASE.

If not Trailcon unit, do not change logic.

**Comment by d3sqa** [comment]
The customer name has been removed from Quote verification screen. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/13773517/61b1caa8-eabb-11e5-89ea-e1df588898a1.png)

At RO detail screen, of the unit is Trailcon owned, customer from last RTMI will be displayed. If the unit is not Trailcon owned, then the customer field will be blank

MRO debug updates will be made available soon

**Comment by d3sqa** [comment]
MRO application updates are now available

**Comment by giovanicani** [comment]
**The customer logic is not working.**

Take preferred # 305323 (UAT uni_id 31602876) for example.

Mobile is suggesting customer Trailcon as customer
![image](https://cloud.githubusercontent.com/assets/5666297/13920327/d390c908-ef48-11e5-8308-89c94e9a19a4.png)

However last RTMI is open under customer **Dollarama**. Quote should have suggested **Dollarama** as customer.
![image](https://cloud.githubusercontent.com/assets/5666297/13920372/0e869650-ef49-11e5-84e3-c69211982221.png)

**Logic again (should apply when creating Quotes on MOBILE and CLOUD)**

1. If non-Trailcon unit: Customer suggested is the owner of the unit;

2. If Trailcon unit: Customer suggested should be:

a. If an RTMI is not voided AND type in (LEASE, RENTAL) AND inbound_approved_date then use the customer from the RTMI.

b. If (a), not found, then look for last(inbound_approved_date) not voided RTMI where type in (LEASE, RENTAL)

c. If (b) not found then use Trailcon as last resource.

**Comment by d3sqa** [comment]
@giovanicani, we are displaying customer of last RTMI in status ININSPECTAPPROVED i.e. an inbound approve date is present against the RTMI. The screenshot that you have attached is in OUTINSPECTAPPROVED, therefore, the given customer is not displayed as per our logic

Regarding point b, isn't it same as point a ? Are you referring to outbound_approved_date instead of inbound_approved_date ?

**Comment by d3sqa** [comment]
Incorporated outbound_approved_date as well in both Quotes and MRO. Please see screenshots below:

![screenshot_13](https://cloud.githubusercontent.com/assets/13255706/13944064/bd970afa-f023-11e5-854a-73ae0ef868db.png)

![screenshot_14](https://cloud.githubusercontent.com/assets/13255706/13944068/c1736092-f023-11e5-921f-89709d1ac820.png)

**Comment by giovanicani** [comment]
As per conversation...

![image](https://cloud.githubusercontent.com/assets/5666297/13950942/50ad72d6-f004-11e5-834f-328b2d368935.png)

**Comment by giovanicani** [comment]
Assigned to Tufail as per conversation. Some tweaks are necessary.

**Comment by d3sqa** [comment]
Above requirement has been incorporated. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Still not working: points B and C not working at all.

TRAILCON OWNED - Last customer that returned the unit is not showing up on the customer box by default
<img width="1310" alt="screen shot 2016-03-25 at 9 26 08 am" src="https://cloud.githubusercontent.com/assets/5666297/14046670/2c9cf41c-f279-11e5-9d39-132f6a6cfc94.png">

CUSTOMER - OWNED - Owner customer not showing up on box.
<img width="1025" alt="screen shot 2016-03-25 at 9 38 00 am" src="https://cloud.githubusercontent.com/assets/5666297/14046671/2c9f3128-f279-11e5-8b0a-0a80faf5167d.png">

**Comment by giovanicani** [comment]
# Still does not work. Owner is Walmart but customer box is coming blank.


<img width="1085" alt="screen shot 2016-03-25 at 3 46 59 pm" src="https://cloud.githubusercontent.com/assets/5666297/14052528/6534534c-f2a1-11e5-9ad6-aac9fc9e8312.png">

**Comment by d3ssupport** [comment]
For non TC unit it will be blank this logic not change as you also mentioned in ticket " unit is trailcon that customer from last rtmi if unit is non trailcon customer field will be blank" . Please provide feedback on it. 



-------- Original message --------

**Comment by giovanicani** [comment]
works thanks!
