### ISSUE TITLE
Cloud & Mobile: Set default SHIFT CODE for labour

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#173]
On the MRO, is there a logic to set the Shift code on labour ? Or it is always Regular by default ?

Please apply same logic on the mobile Quote.

On the Cloud, make it always Regular when creating a new labour line (instead of blank)

![image](https://cloud.githubusercontent.com/assets/5666297/13937893/180916ac-ef9f-11e5-9306-29a632aad6ad.png)

![image](https://cloud.githubusercontent.com/assets/5666297/13937910/49b7aefc-ef9f-11e5-941e-12e571a936f5.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The shift is now 'Regular' by default at both Quotes (Cloud and Mobile). Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works. thanks! Validated!
