### ISSUE TITLE
Unable to upload pictures on Quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#174]
Please work on issue below... upload picture but nothing happens.

![image](https://cloud.githubusercontent.com/assets/5666297/14116969/67e7e628-f5b0-11e5-9cd9-208c5e6c12a8.png)

**Comment by giovanicani** [comment]
Issue 1520 on zendesk

**Comment by d3ssupport** [comment]
Issue has been fixed.

**Comment by giovanicani** [comment]
awesome, thank you!
