### ISSUE TITLE
Bug: When creating Quote from RTMI with a customer that has ' on its name, Quote wont save

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#175]
Example on production Q000451. Customer 595 - MUIR'S CARTAGE LTD.

I had to remove the single quote on the database in order to save and assign to mechanic.

**Please make sure that single quotes do not cause isse**

**Comment by d3sqa** [comment]
Done. The quote created from RTMI is now successfully saved. 
Fix has been deployed at production
