### ISSUE TITLE
Cloud: Create ROs from Quote : Popup window not functional

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#18]
Entire screen not usable.

![image](https://cloud.githubusercontent.com/assets/5666297/11851612/7fc68d9a-a401-11e5-893d-ada9d5132a31.png)

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by d3sqa** [comment]
Pop up window is now functional. ROs are now created successfully from a quote. The labours that are dragged and dropped from Quote are reflecting against the newly created RO.

However, the parts are not displayed against the labours for the given RO. Work in progress on this feature

**Comment by d3ssupport** [comment]
Done, Parts are now displaying against labours for the given RO. Ready for testing in Development.

**Comment by giovanicani** [comment]
not working at all! Added 3 labours to RO, created RO, and RO had only 1 labour.

Drag and drop functionality not working well... if it can't be fixed then need to add button to move one or all.

![image](https://cloud.githubusercontent.com/assets/5666297/12097688/04d6c85e-b2eb-11e5-8463-fedb38a30d40.png)

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by d3ssupport** [comment]
checked and confirmed and works fine wit us, will test together

**Comment by giovanicani** [comment]
working on the latest test. Will monitor. close for now.
