### ISSUE TITLE
Cloud: Only show active users on the assign to drop down list

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#19]
![image](https://cloud.githubusercontent.com/assets/5666297/11852406/c8f40430-a405-11e5-9f8c-2d4a60dc2985.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Only Active users will be displayed at the 'Assigned To' drop down. Fix is available at development environment. It will be available at the UAT environment with the upcoming release

**Comment by giovanicani** [comment]
will test and provide feedback.

**Comment by giovanicani** [comment]
need to validate when code moved to uat.

**Comment by giovanicani** [comment]
done.
