### ISSUE TITLE
Cloud: Hourly Rate (labour) and Charge (parts) needs to allow inline edit

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#2]
![image](https://cloud.githubusercontent.com/assets/5666297/11847995/11b69c40-a3ee-11e5-89d8-77e756aaf297.png)

**Comment by d3sqa** [comment]
Inline editing for Hourly Rate (Labour) and Charge $ (Parts) has been implemented in development environment. The fix will be available at UAT in the upcoming release

![image](https://cloud.githubusercontent.com/assets/13255706/11911998/9c74fc82-a64b-11e5-980a-8c429281ddf6.png)

![image](https://cloud.githubusercontent.com/assets/13255706/11912005/aec4dca4-a64b-11e5-8970-f55d0e2a335d.png)

**Comment by giovanicani** [comment]
Not saving!! After changing, pressing SAVE and closing, when opening new rate was not saved.

Not working!!

**Comment by d3sqa** [comment]
Inline editing for Hourly Rate and Charge are saved directly after inserting value in development environment. 

![screenshot_571](https://cloud.githubusercontent.com/assets/13255706/12016860/ef674062-ad71-11e5-8c08-9f420f72b124.png)

![screenshot_572](https://cloud.githubusercontent.com/assets/13255706/12016865/f88d7256-ad71-11e5-9da5-220363319361.png)

Need further discussion on this issue.

**Comment by giovanicani** [comment]
seems to be working now.
