### ISSUE TITLE
Cloud: Add Contact Search box

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#21]
Search by contact name, e-mail or customer name

![image](https://cloud.githubusercontent.com/assets/5666297/11852507/4229234e-a406-11e5-8146-742812687f73.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
Please also do the search by the vendor column.

**Comment by d3sqa** [comment]
Search by Vendor column has been done at development. The fix will be available at UAT in next release

![image](https://cloud.githubusercontent.com/assets/13255706/11892031/2012dee0-a586-11e5-83ea-5db48c932762.png)

**Comment by giovanicani** [comment]
done.
