### ISSUE TITLE
Cloud: Change verbiage of empty field

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#22]
As discussed on our latest meeting:

Change verbiage to: "Email addresses should be separated by , or ;"

![image](https://cloud.githubusercontent.com/assets/5666297/11852548/7cbda69c-a406-11e5-9400-d098d1473409.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Verbiage has been changed. The fix is available at development environment and will be available in next release at UAT

![image](https://cloud.githubusercontent.com/assets/13255706/11868449/aa737a0c-a4d9-11e5-99a9-7a3585dd9c8a.png)

**Comment by giovanicani** [comment]
looks good thanks.
