### ISSUE TITLE
Cloud: Email field should be editable

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#23]
Email field should be editable.

Once saved, if email not existent on the contact table then add with the following info:

Type: TO
Name: N/A (will have to be updated later on by user)

![image](https://cloud.githubusercontent.com/assets/5666297/11852602/dddef570-a406-11e5-9a92-c8361b19c8f4.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Email field has now been enabled at both Create and Edit Quote forms. The emails will be displayed if there exist any against the customer. If not, 'N/A' will be displayed. Done at Development environment and will be available in the upcoming release at UAT Environment

**Comment by giovanicani** [comment]
will test and provide update.

**Comment by giovanicani** [comment]
Doesn't seem to be working... added my email on the email box, but when I go into the contact list window, I don't see my email there.

![image](https://cloud.githubusercontent.com/assets/5666297/11875923/0fdff2a0-a4b5-11e5-8d39-986f27af3131.png)

**Comment by giovanicani** [comment]
any update?

**Comment by d3sqa** [comment]
Fixed. Done at Development Environment. It will be available in the next release at UAT.

**Comment by giovanicani** [comment]
during the meeting with Anwar and Tufail we noticed on Q001176, that the email "gary@trailcon.com", got duplicated after sending the email.

**Comment by d3sqa** [comment]
Done at Development Environment. It will be available in the next release at UAT.

**Comment by giovanicani** [comment]
works. thanks.
