### ISSUE TITLE
Cloud: Add Quote link on the MRO Screen

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#24]
1. Reduce space between label and field
2. On the RO #, create another box and place the Quote Number (if RO was created by Quote)
3. Quote #, should be an hyperlink that opens the quote on a separate tab.

![image](https://cloud.githubusercontent.com/assets/5666297/11853546/aa9c829e-a40c-11e5-8af6-5b415d02e71b.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Following changes have been done at Development environment and will be released in next release at UAT:

1. Reduce space between label and field
2. On the RO #, create another box and place the Quote Number (if RO was created by Quote)
3. Quote #, should be an hyperlink that opens the quote on a separate tab

![image](https://cloud.githubusercontent.com/assets/13255706/11868130/86e2629e-a4d7-11e5-98c1-16737c9d8405.png)

**Comment by giovanicani** [comment]
looks very good... thanks
