### ISSUE TITLE
Cloud & Mobile: Part number not mandatory

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#25]
Part number not mandatory when creating quote, user can enter something on the notes. This is required for situations where the part number if not in our system, or is not known at the time they are building the quote.

This change is valid for Cloud and Mobile

***Note that part # is required when quote being approved, internally (2 check boxes)***

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done on Mobile side at Development Environment. It will be available in the next release at UAT. 
However, work is in progress on Cloud side

**Comment by d3sqa** [comment]
Part addition without part # feature has been done at cloud side as well at Add and Edit Quote forms. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12141545/35e98af0-b492-11e5-9549-25f344d7fc8a.png)

**Comment by giovanicani** [comment]
Giovani to test.

**Comment by giovanicani** [comment]
working. closing ticket.
