### ISSUE TITLE
Cloud: Validations when Approving

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#26]
When one of the 2 approval check boxes are checked, please add the following validation

Type of message: Warning (allow user to proceed with approval)
Check if there are labour with no parts, if there are, show message:  "Labour line [labour desc] doesn't have any parts." [OK - Proceed with Approval] [Cancel]

Note that there could me multiple labours without parts, please add them all into the same message.

Type of message: Error (does not allow user to proceed with approval)
Check if there are any part without a par_id, if there are, raise error and do not proceed.

**Comment by giovanicani** [comment]
Please enter add the 2 validations above on the Trailer Internal Approval and Reefer Internal Approval on the WorkFlow tab. When approving the system will also save the form.

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
please provide update on this thread.

**Comment by d3sqa** [comment]
Work has been done on relevant validation messages i.e.

1. When Labour line has no parts, a message would be prompted and user would be allowed to proceed
2. When Labour line has a part without part #, the user won't be able to proceed

![image](https://cloud.githubusercontent.com/assets/13255706/12167410/d639033a-b54d-11e5-8498-68ca11f94d3d.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12167433/ed31cc66-b54d-11e5-9b9d-4cf8e0a38b2b.png)

**Comment by giovanicani** [comment]
On the warning message, change the button OK to "OK - Proceed with Approval". This was requested on my email above.

**Comment by d3sqa** [comment]
Button has been renamed. Please check the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12191626/c6ef7fde-b5f8-11e5-9636-f4f1d76a3f86.png)

**Comment by giovanicani** [comment]
good thanks.
