### ISSUE TITLE
Cloud: Work flow, change / add verbiage

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#27]
Replace the check box below...
![image](https://cloud.githubusercontent.com/assets/5666297/11876393/87ed518c-a4b7-11e5-9a68-990f04bb65ff.png)

with:

[   ] Trailer - Quote Reviewed Internally and Approved to sent to Customer
[   ] Reefer - Quote Reviewed Internally and Approved to sent to Customer

These 2 are mandatory based on the Reefer / Trailer check box at the top.

**Comment by d3ssupport** [comment]
Workflow related Task.

**Comment by giovanicani** [comment]
done.
