### ISSUE TITLE
Cloud: Add PM Info (Read Only)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#28]
Giovani to add more details on the select statement.

PM Information will allow the service manager to create the proper labour lines for the job.

**Comment by giovanicani** [comment]
![image](https://cloud.githubusercontent.com/assets/5666297/11879495/b0f64fc2-a4c9-11e5-8e11-3bf31ea2644f.png)

**Comment by giovanicani** [comment]
Here is the query:
```sql
SELECT LISTAGG(vmrsys.code||'-'||vmrsysass.code|| ' - Last Check: '|| CAST(maidue.last_Date AS DATE) || '  Due next: ' || CAST(maidue.due_date AS DATE) ||
CASE WHEN CAST(maidue.due_date AS DATE) < SYSDATE THEN ' **OVERDUE** ' ELSE '' END,CHR(13)) WITHIN GROUP (ORDER BY uni_id) pm_line
FROM pm_maintenance_dues_wv maidue 
JOIN pm_vmrs_system_assemblies_wv vmrsysass ON maidue.vmrsysass_id = vmrsysass.vmrsysass_id
JOIN pm_vmrs_systems_wv vmrsys ON vmrsysass.vmrsys_id = vmrsys.vmrsys_id
WHERE uni_id = :quote_unit_id;
```

![image](https://cloud.githubusercontent.com/assets/5666297/12092762/0e9f14e0-b2cd-11e5-92b0-9677201b9176.png)

**Comment by d3sqa** [comment]
PM Information field in Read Only mode has been added to the Add Quote and Edit Quote forms. For those which are overdue, data would be shown in Red and those whose due date has not been reached yet will be displayed in black color.

Please see below screen shots:

![image](https://cloud.githubusercontent.com/assets/13255706/12110221/b2a9a800-b3ab-11e5-9b2e-c333a2a24fd2.png)


![image](https://cloud.githubusercontent.com/assets/13255706/12110226/bd75e474-b3ab-11e5-8c19-443650059241.png)

**Comment by giovanicani** [comment]
OK, looks good, just do the following tweak:

Remove "Check"
Remove "next"
Remove "OVERDUE"

I am trying to make it all on the same line.
PM-A - Last: 04-Aug-05 Due: 02-NOV-15

** Also make sure font is the same as the field label. Label font seems to be slightly smaller. **

**Comment by d3sqa** [comment]
Removed "Check"
Removed "next"
Removed "OVERDUE"

![image](https://cloud.githubusercontent.com/assets/13255706/12141943/e05b6ae6-b495-11e5-8d0d-b638e0ec2efc.png)

The data is now displayed in a single line. Ready to test in development environment

**Comment by giovanicani** [comment]
looks great. thanks!
