### ISSUE TITLE
Cloud: Date Edit

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#3]
Provide a calendar interface for user to change date / time on the cloud.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The 'Date/Time' field at Create/Edit RO forms is now enabled. The user can change the date and/or time while creating a quote (which will be converted based on user's timezone). At the edit quote, the edited date will successfully be reflected when the form is retrieved back. 
Done at development environment
