### ISSUE TITLE
Cloud: Dashboard - Add a column with Yard Location

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#30]
Add a column with Yard Location. Giovani to add more details.

**Comment by giovanicani** [comment]
Add location and status as it was done on the reservation grid. See picture below.

![image](https://cloud.githubusercontent.com/assets/5666297/12093951/e350dfd8-b2d3-11e5-845e-60d3cb183716.png)

**Comment by d3sqa** [comment]
Location/Status column has been added to the Quote Dashboard screen. Please refer to the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12113476/d41ee04a-b3c4-11e5-8651-abe34f6c7ff9.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
looks good. thanks
