### ISSUE TITLE
Cloud: Quote Dashboard Filters & Default Values

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#35]
By default users should only see records for their Location (Branch)

Further filters TBD.

**Comment by d3sqa** [comment]
Only the records with the location same as that of the user are now displayed at the Quote Dashboard screen. Done at development environment. 
It will be available at the UAT in the upcoming release.

**Comment by giovanicani** [comment]
Guys. Location should be a filter. User should be able to see all of required. 

--
Giovani Cani

**Comment by d3sqa** [comment]
@giovanicani, kindly give your feedback on the following:

Currently, there is a filter applied on the Quote List/dashboard based on user location i.e. Calgary's user will only see Calgary records. Now if we provide Location in filter, this check will be of no use. Can we remove the default user location based filter from the list? In this case, the Search will be applied via the filter only.

Also, will this feature be done on both Quote Listing and Quote Dashboard ?

**Comment by giovanicani** [comment]
Apply on quote listing for now. Later on we will also need to apply on dashboard. 

Please make location a filter that user can select between a specific branch or all (drop down list). By default should show all quotes for the users default branch. 

Please let me know if there are still questions on this. 

--
Giovani Cani

**Comment by d3sqa** [comment]
The Location has been added to the filter. At first, when the listing is loaded, the records are populated based on the user location. Later, when a location is selected from the filter, all the records based on the location given in the filter are retrieved.

This feature has been implemented at Quote Listing and is ready to be tested in development environment

**Comment by giovanicani** [comment]
Pending dashboard changes.

**Comment by d3sqa** [comment]
Discussion required regarding implementation of filter at Quote Dashboard's screen

**Comment by giovanicani** [comment]
Add the following workflow status grid and respective Quotes:

**QUOTE STARTED**
BACKGROUND COLOR: Pale Purple (#d4c5f9)

**WAITING ON VENDOR**
BACKGROUND COLOR: Yellow (#fbca04)

**TCL REEFER APPRVL PENDING**
BACKGROUND COLOR: Orange (#eb6420)

**TCL TRAILER APPRVL PENDING**
BACKGROUND COLOR: Orange (#eb6420)

**SEND TO CUST. PENDING**
BACKGROUND COLOR: Red (#fc2929)

**CUST. APPRVL PENDING**
BACKGROUND COLOR: Yellow (#fbca04)

**CUST. APPRVL PENDING - OVERDUE**
BACKGROUND COLOR: Red (#fc2929)

**MRO REVIEW AGAINST QUOTE PENDING**
BACKGROUND COLOR: Orange (#eb6420)

**BILL AS PER QUOTE PENDING**
BACKGROUND COLOR: Pale Green (#bfe5bf)

**Comment by d3sqa** [comment]
The Quote statuses along with background colors are incorporated at Quote Dashboard scree. Please see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12346045/625c2228-bb72-11e5-91ab-cb99074fe73c.png)

**Comment by giovanicani** [comment]
done.
