### ISSUE TITLE
Cloud & Mobile: Note Tweaks

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#36]
Cloud
-------
1. Change emptyText of the Internal Notes to "Notes ONLY available on the Cloud. Enter information about reasoning for a special rate, # of hours, billing references, etc..."
2. Change label of the Notes to "Notes (Shown on Customer Reports)", change emptyText to "Notes viewable by customers. Enter information that will help the customer better understand the quote."
3. Create new note called Dispatch, with the following label "Dispatch Notes", emptyText should be "Read only notes available on the mobile application. Enter information such as priority of the work, location of the equipment, etc..."
4. Make the 3 boxes with the same size, and on the following order: Dispatch Notes, Internal Notes and Notes

![image](https://cloud.githubusercontent.com/assets/5666297/12012665/08348ea6-accd-11e5-9bc5-357ee30beaf0.png)

Mobile
--------
1. Add Dispatch Notes on the Inquiry screen for Quotes. Make it a tooltip, or a button or a multi line text field - read only.
2. On the Quote Detail screen, show Dispatch Notes (read only) and Notes. Internal notes should no longer be shown on the mobile app

![image](https://cloud.githubusercontent.com/assets/5666297/12012653/b53959fc-accc-11e5-9b18-aab6698cf514.png)

**Comment by giovanicani** [comment]
still thinking on this one....

**Comment by d3sqa** [comment]
Done on Cloud side at Development Environment. It will be released in the next release at UAT. 
To be discussed with @giovanicani  on Mobile side.

**Comment by giovanicani** [comment]
Looks good on the Cloud.

**Comment by giovanicani** [comment]
Still work pending on mobile.

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by d3sqa** [comment]
Work done on mobile side as well. Please see below screenshots:

![image](https://cloud.githubusercontent.com/assets/13255706/12142001/6cc0f118-b496-11e5-9248-c5665f4af0bb.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12142007/7bfd5108-b496-11e5-8067-f92bc6bd5165.png)


Ready to test in development environment. The fix will be available in the upcoming debug

**Comment by giovanicani** [comment]
OK, I am waiting on the new mobile release to test.

**Comment by d3sqa** [comment]
The fix is now available at UAT. Please update existing debug to test it
The debug is also placed at the download center

**Comment by giovanicani** [comment]
looks good. thanks!
