### ISSUE TITLE
Cloud: Add "Add Another" feature to labour lines as well.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#37]
As it was done with the parts section, please add the "Add Another" feature to the labour as well as users often enter many labours at once, and this will save them time.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The 'Add Another' feature has been incorporated at Labour grid for both Add and Edit Quote forms. Ready to test in development environment

**Comment by giovanicani** [comment]
works. thanks.
