### ISSUE TITLE
Cloud: Quote from RTMI

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#38]
We will no longer import images from RTMI automatically via the RTMI screen.

1. Remove checkbox and change verbiage to say that user needs to import images from the Quote screen.

Giovani to provide verbiage.

**Comment by giovanicani** [comment]
Verbiage: "Please import images from the Quote Detail screen."

**Comment by d3sqa** [comment]
Checkbox has been removed and verbiage has been added

![image](https://cloud.githubusercontent.com/assets/13255706/12089296/2c81d758-b305-11e5-80de-1a55d7abc227.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
Why there is still this message ?? Please remove and make the new message in red. Thanks.

![image](https://cloud.githubusercontent.com/assets/5666297/12089817/c796f9d4-b2b6-11e5-97e5-bb62b95119fc.png)

**Comment by d3sqa** [comment]
Please check now

![image](https://cloud.githubusercontent.com/assets/13255706/12107543/3e8d26a8-b38e-11e5-897f-e49ecd7659f6.png)

**Comment by giovanicani** [comment]
looks good thanks.
