### ISSUE TITLE
Mobile: When barcode not found, license plate not mandatory

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#4]
Please only have the Trailer # (Preferred) for user to select from a drop down list. Drop down list should have preferred number, owner, license plate.

![image](https://cloud.githubusercontent.com/assets/5666297/11848088/a8f5f678-a3ee-11e5-97e4-3769e13c6232.png)

**Comment by d3sqa** [comment]
@giovanicani, currently we are not bringing the YM_UNITS table during full sync, so this table is not retrieved in our local sqlite database. For this reason, we can't provide drop down list currently. 

In order to display a drop down list, we need to bring YM_UNITS table during full sync. Please give your feedback on this

**Comment by giovanicani** [comment]
Yes you are Right. 

Let me think a bit more on this. 

--
Giovani Cani

**Comment by giovanicani** [comment]
Let's do the following ... (If barcode not found)

Allow user to enter Trailer # (preferred #) if only one is found then go to the next screen to confirm info (as is now). If more than one ACTIVE unit is found. Then show a popup for user to select. On the popup have the license plate, year and owner. 

Let me know if this would work for you. 

--
Giovani Cani

**Comment by d3sqa** [comment]
Done at Development Environment. It will be available in the next release at UAT.
![screenshot_584](https://cloud.githubusercontent.com/assets/13255706/12050437/4e63876e-af17-11e5-9a2b-532a44e67dac.png)

**Comment by giovanicani** [comment]
Thanks, Giovani to review once moved into UAT.

**Comment by giovanicani** [comment]
Guys, please do the following tweaks:

1. On the screen that shows multiple units if they have the same preferred number, please add the following verbiage at the top: "Multiple units were found with the same Trailer Number, select the unit from the list below: "

1.1 Please make the list taller, there is plenty of space

2. On the screen below, make the cursor go by default on the trailer number, and add (*) after the Trailer Number label, to indicate that this is a mandatory field - "Enter Trailer # (*)".

![image](https://cloud.githubusercontent.com/assets/5666297/12236056/a621bda4-b845-11e5-85b8-8d98aa672340.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The cursor will be on the Trailer # field when the screen opens up. () have been added. See below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/12255479/ed3ebc3e-b915-11e5-91c7-c304c79c91b9.png)

List's height has been increased and verbiage has been added. See below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/12255488/0c5b80c0-b916-11e5-9440-d4f1d7d30473.png)

Done and ready to test

**Comment by giovanicani** [comment]
Guys, it was supposed to be (*), not (), GITHUB changed what I typed. Please add an start in the middle of the parenthesis.

**Comment by giovanicani** [comment]
fixed.
