### ISSUE TITLE
Cloud: Contact Listing, search needs to be move to server side

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#40]
On the contact list, when searching for a contact that is not on the same pagination, the result returns zero results eventhough there is a record that match that criteria.

Speaking to Anwar, he mentioned that the search needs to be moved to server side.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Now the results will be returned irrespective of on which page # it is present. Searching based on server is implemented at Development environment. It will be available in next UAT release

**Comment by giovanicani** [comment]
Why the following string returns me results ?
Why pressing enter closes the screen ??
@tufailzafar @TeqdirectGene - I need better testing!! This are simple things that need to looked at.

![image](https://cloud.githubusercontent.com/assets/5666297/12081464/d343f224-b247-11e5-99a8-dea657652e43.png)

**Comment by d3sqa** [comment]
Please check now. No result set will be returned when invalid data is entered. By pressing the enter key, window won't be closed now

![image](https://cloud.githubusercontent.com/assets/13255706/12089307/4ac75b2a-b305-11e5-9b9a-c61ce65b481d.png)

**Comment by giovanicani** [comment]
works now. thanks.
