### ISSUE TITLE
Cloud: Add PO Required and Billing Notes Reminder

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#42]
Please see image below. Add reminders as shown on the image.

Make sure that users can read all billing notes and nothing is hidden. These reminders will be based on the customer selected

![image](https://cloud.githubusercontent.com/assets/5666297/12092328/66556a66-b2ca-11e5-94a2-7cd245524c30.png)

**Comment by d3sqa** [comment]
We are displaying data as per below screen shot but it is not looking good as the text looks messed up:

![image](https://cloud.githubusercontent.com/assets/13255706/12114743/1cb7e87a-b3ce-11e5-905b-1d7b84d9dc6d.png)


We have devised a work around for it, created a new tab namely 'Billing Notes'. In this tab we will display the entire text and will show one line text proceeded by ... above the form.

![image](https://cloud.githubusercontent.com/assets/13255706/12114775/67e66d1c-b3ce-11e5-8b7f-a2e465b04706.png)


Done at Edit Quote form. Ready to test in development environment

**Comment by giovanicani** [comment]
As discussed, please make it so that all the note is visibile to the user right on the header. No need for Billing Notes tab.

**Comment by d3sqa** [comment]
All notes are now displayed at the Edit Quote form header. Ready to test in development environment

**Comment by d3sqa** [comment]
The billing notes are also displayed at the Add Quote form now. Please see below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/12139756/591e6ed6-b484-11e5-903f-38362a051fe8.png)

**Comment by giovanicani** [comment]
works thanks.
