### ISSUE TITLE
Cloud: Unit Info on insert form

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#43]
Unit info on insert form should be the same as the update form. Fields on the image below are incorrect. License plate cannot be updated via this form.

![image](https://cloud.githubusercontent.com/assets/5666297/12097511/0666fac8-b2ea-11e5-89c6-21c60ef0075d.png)

**Comment by d3sqa** [comment]
The Unit Information section at both Add and Edit Quote forms is now same. Ready to test in development environment

**Comment by giovanicani** [comment]
Giovani to verify.

**Comment by giovanicani** [comment]
looks ok. thanks.
