### ISSUE TITLE
Cloud: Customer notes not appearing on the Quote Report

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#44]
Please add the multi-line customer notes on the quote report, as per image below...

![image](https://cloud.githubusercontent.com/assets/5666297/12098544/fdd6b806-b2f0-11e5-9c2f-4f8ec0988501.png)

**Comment by d3sqa** [comment]
Customer notes are now displayed on the Quote Report. Ready to test in development environment.
Please find the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12111749/8ce3b4cc-b3b9-11e5-9eed-a60da21ba3c9.png)

**Comment by giovanicani** [comment]
looks ok, thanks
