### ISSUE TITLE
Cloud: Remove NA from email box when there is no email for customer

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#45]
![image](https://cloud.githubusercontent.com/assets/5666297/12116091/4440be88-b385-11e5-8c91-eb096d1b3e2f.png)

**Comment by d3sqa** [comment]
N/A will not be displayed while adding or editing the customer. It will be displayed only when the form is saved. Ready to test in development environment

**Comment by giovanicani** [comment]
N/A should be on this field at ALL. Should be blank or with emails.

Please remove N/A

**Comment by d3sqa** [comment]
N/A has been removed. The Email field will remain blank if there exist no emails. Ready to test in development environment

**Comment by giovanicani** [comment]
ok. ticket closed.
