### ISSUE TITLE
Cloud: When adding labour, no image icon should be shown

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#47]
Image icon only visible if there is an image to that labour line.

![image](https://cloud.githubusercontent.com/assets/5666297/12116178/d8883580-b385-11e5-86e8-7e39173c3b2d.png)

**Comment by giovanicani** [comment]
Can I please get an update on this ?

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
resolved.
