### ISSUE TITLE
Cloud: On Insert Form for parts, Notes box is missing

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#48]

**Comment by d3sqa** [comment]
Work in progress
Part box has been added and notes are displayed however there is an issue regarding the last part's notes reflecting in the Part's box for the next labour line. We are working on it

**Comment by giovanicani** [comment]
okay thanks for the update.

**Comment by d3sqa** [comment]
Part Notes field has been displayed on Insert form. Notes are now successfully displayed against the parts. Ready to test in development environment

**Comment by giovanicani** [comment]
Giovani to test.

**Comment by giovanicani** [comment]
works. ticket will be closed.
