### ISSUE TITLE
Report : Add Branch information onto the Quote Report

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#49]

**Comment by giovanicani** [comment]
Please do the following changes on the Quote report as outlined on the image below:

1. Add at the top the branch info, from rla_locations (remove chr10+chr13 from address). The address should be based on the Branch (location) the report is being associated with.
2. Re-arrange quote date and number
3. Add Expiration date, which is Quote Date + 60 days.
4. Remove N/A
5. Remove readings line
6. Make sure that the make / model / year are populated.

![image](https://cloud.githubusercontent.com/assets/5666297/12119953/a0c66a4c-b39c-11e5-8e52-d208fe99cdff.png)

**Comment by giovanicani** [comment]
Also, please make sure that labour / part notes are in the report.

**Comment by d3sqa** [comment]
The above written changes have been done at report. Ready to test in development environment.

Please let us know which email address to be placed in the highlighted section in below screenshot:

![screenshot_17](https://cloud.githubusercontent.com/assets/13255706/12141692/8c033b1a-b493-11e5-9d06-3ec64fbc12df.png)

**Comment by giovanicani** [comment]
that is the correct email. No further changes required.
