### ISSUE TITLE
Cloud: Add Brief Desc. field on the Quote Listing

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#5]
Add after reference number.

![image](https://cloud.githubusercontent.com/assets/5666297/11849522/4a22b304-a3f6-11e5-93fc-f52b4ac1f01f.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Bried Desc field is now displayed right after the Reference # column at the Quote Listing grid. It is done at development and will be available at UAT in the upcoming release

![image](https://cloud.githubusercontent.com/assets/13255706/11868856/a86ee0c2-a4dc-11e5-8040-b948024e902c.png)

**Comment by giovanicani** [comment]
looks good thanks!
