### ISSUE TITLE
D3S: Email details

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#50]
@d3ssupport @tufailzafar 

As discussed during the meeting today:

1. The requirements is that we will be using one system email user to send all emails from D3S. I believe this is already been done with the RTMI Email feature.

2. From and Reply To, must be from the user that is sending the email. Example: gcani@trailcon.com, etc... We have to do some tests to make sure that because the authenticated user is different from the FROM / REPLY TO, we don't get flagged as SPAM by servers out there on the internet.

3. If a quote is sent to 10 users and only one is undeliverable, all 9 should receive the email, and the sender should receive an email on their outlook saying that 1 email (with details) was not delivered.

@TeqdirectGene Please have Erik and Ashley review this to make sure they agree or have anything else to add.

Thanks!

**Comment by giovanicani** [comment]
Just adding to the comment above. I don't believe we will need a SPF record as the sender domain will still be trailcon.com.

**Comment by giovanicani** [comment]
As discussed on this morning's meeting @TeqdirectGene kindly discuss this with your guys and let us know. Thanks

**Comment by TeqdirectGene** [comment]
Giovani: Erik has the info now, checking and then we will confer with Ashley. Want to make sure every email is correct, and being archived.  Thanks, gene

**Comment by TeqdirectGene** [comment]
Giovani: Erik has the info now, checking and then we will confer with Ashley. Want to make sure every email is correct, and being archived.  Thanks, gene

**Comment by giovanicani** [comment]
Gene to talk to Tufail, after today's meeting to get the script details, so that we can have a meeting with Ashley, Giovani, Gene and Tufail to finalize the email transmission. Make sure that is not caught as SPAM by internet "police".

**Comment by giovanicani** [comment]
Gene still working on it.

**Comment by giovanicani** [comment]
Gene still working with Erik on this. Giovani has shown the SMTP2GO interface.

**Comment by giovanicani** [comment]
Erik has done research and found a way to make sure that:

1. Emails are not caught in spam filters.
2. When sending to several recipients, if one is invalid, all others will receive email
3. Sender will receive undelivery notification for the invalid email.
