### ISSUE TITLE
Cloud: Audit Log needs to track **ALL CHANGES**

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#52]
Audit log must track all changes:

All updates, all changes, including but not limited to:

Quote date changes.
Workflow (checks and un-checks).
Assignments.
Labour inserts and updates.
Parts inserts and updates.
Track email sent, and addresses that was sent to.

**Comment by d3sqa** [comment]
1. Adding and updating labour line information are now logged at audit log
2. Adding and updating part information are now logged at audit log
3. Quote date changes will be logged at audit log

However, the audit log is not updated in real time currently i.e. the user needs to refresh the form first to get the updated activity log. We are working on it

Also, work is in progress on Workflow, assignments, and email tracking logs

**Comment by d3sqa** [comment]
Email sending activity along with email addresses to which the email has been sent is now logged at audit log. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12261971/5d8875e0-b946-11e5-8216-31587cc0e9db.png)

**Comment by giovanicani** [comment]
@d3sqa are all changes now recorded on the audit log ?

**Comment by d3ssupport** [comment]
All changes now recording in audit log, only work flow remaining

**Comment by giovanicani** [comment]
okay thanks. Will test and provide feedback.

**Comment by giovanicani** [comment]
Change date not logged on Audit Log
Adding / updating / removing notes not logged on Audit Log.

***ABSOLUTELY EVERY CHANGE MUST BE LOGGED*** PLease do this ASAP.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Please see below images of activities being logged at Audit Log:

![auditlog1](https://cloud.githubusercontent.com/assets/13255706/12291195/be0f69e8-ba07-11e5-83aa-af9827e16c1b.png)

![auditlog2](https://cloud.githubusercontent.com/assets/13255706/12291291/2d8c3256-ba08-11e5-990f-86b96ba8895c.png)

![auditlog3](https://cloud.githubusercontent.com/assets/13255706/12291453/2bce098e-ba09-11e5-9ec8-3576ba396309.png)

![auditlog4](https://cloud.githubusercontent.com/assets/13255706/12291664/5fb98b50-ba0a-11e5-9bd2-0e1e5938a9a1.png)

![auditlog5](https://cloud.githubusercontent.com/assets/13255706/12291725/ce8075da-ba0a-11e5-8cd7-7b270ead028c.png)

![auditlog6](https://cloud.githubusercontent.com/assets/13255706/12291787/25585bde-ba0b-11e5-980e-f50a202d8fbc.png)

![auditlog7](https://cloud.githubusercontent.com/assets/13255706/12292022/70730398-ba0c-11e5-9b1f-8a49bb6894f1.png)

![auditlog8](https://cloud.githubusercontent.com/assets/13255706/12292144/1dbf85ee-ba0d-11e5-88a6-457abb844635.png)

Ready to test in development environment

**Comment by d3sqa** [comment]
Things which are still in progress:

- Email update activity when existing email is edited.
- New email when added if existing one is already present, both the emails reflects again in audit log
- Charge ($) inline editing activity at Parts grid

**Comment by d3sqa** [comment]
Currently we are controlling audit log activities through trigger, therefore the user is tracked via 'Assigned To' field because Last_Update_User is updated through table audit trigger with data such as TCS_MOBILE, TCS_USER etc.
The Last_Update_User needs to be updated with logged in user so that we could track exactly which user has updated the record.
So, should be remove Last_Update_User from Audit Trigger ?

![auditlog10](https://cloud.githubusercontent.com/assets/13255706/12293351/c0f56d94-ba14-11e5-951a-a085114cf220.png)

 Awaiting your feedback

**Comment by giovanicani** [comment]
No we should not remove the last_update_user from the Trigger. Let me do some investigation and get back to you.

**Comment by giovanicani** [comment]
Email sent to Tufail in 2014 asking to add the script below at the login stage, if this has been implemented then we can set the program can set the context variable at login time, and DB Trigger can read and update audit table with correct, info.

Waiting on Tufail getting back.

```sql
DECLARE
   par    system_functions_pkg.t_init_params;
BEGIN
   par(1).param_name := 'user_use_id';
   par(1).param_value := :use_id_based_on_login;
   par(2).param_name := 'user_ten_id';
   par(2).param_value := :ten_id_based_on_login;
   par(3).param_name := 'user_cus_id';
   par(3).param_value := :cus_id_based_on_login;
   system_functions_pkg.init_db_params(par); 
END;

**Comment by giovanicani** [comment]
High level example, user as reference

```SQL
APP SIDE ====================================
DECLARE
   par    system_functions_pkg.t_init_params;
BEGIN
   par(1).param_name := 'user_use_id';
   par(1).param_value := '1';
   par(2).param_name := 'user_use_name';
   par(2).param_value := 'gc001';   
   par(3).param_name := 'user_ten_id';
   par(3).param_value := '2';
   par(4).param_name := 'user_cus_id';
   par(4).param_value := '3';
   system_functions_pkg.init_db_params(par); 
END; 

APP SIDE ====================================


DATABASE SIDE ====================================

CREATE OR REPLACE TRIGGER sys_tenants_briu
BEFORE INSERT OR UPDATE ON sys_tenants
FOR EACH ROW 
BEGIN 
   IF inserting THEN
      IF :new.ten_id IS NULL THEN 
         :new.ten_id := oraseq.nextval;
      END IF;
      :new.create_date := systimestamp;
      :new.create_user := NVL(system_functions_pkg.get_context_value('user_use_name'),user);
   ELSE
      :new.last_update_date := systimestamp;
      :new.last_update_user := NVL(system_functions_pkg.get_context_value('user_use_name'),user);
   END IF;
END sys_tenants_briu;
/
show errors trigger sys_tenants_briu;
DATABASE SIDE ====================================

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
We have worked on the audit session to set parameters through user_id by calling the following parameters:

par(1).param_name := 'user_use_id';
par(1).param_value := '1';

We need to do changes in the following procedure:
system_functions_pkg.t_init_params

In order to accept user name as varchar.

par(2).param_name := 'user_use_name';
par(2).param_value := 'gc001';   

We will discuss this in the upcoming meeting.

**Comment by giovanicani** [comment]
sure. thanks!

**Comment by giovanicani** [comment]
Hi Team... I have done the changes on the **sys_functions_pkg package**, kindly see example below:

Any questions or concerns, please let me know... thanks!

```sql
DECLARE
    par    system_functions_pkg.t_init_params;
BEGIN
    par(1).param_name := 'user_use_id';
    par(1).param_value := '24';
    par(2).param_name := 'user_user_name';
    par(2).param_value := 'gc001';
    par(3).param_name := 'user_ten_id';
    par(3).param_value := '1000000';
    par(4).param_name := 'user_cus_id';
    par(4).param_value := '4';
    system_functions_pkg.init_db_params(par); 
END; 
                           
SELECT system_functions_pkg.get_context_value('user_use_id') from dual;
SELECT system_functions_pkg.get_context_value('user_user_name') from dual;
SELECT system_functions_pkg.get_context_value('user_ten_id') from dual;
SELECT system_functions_pkg.get_context_value('user_cus_id') from dual;
```

I had to change the specification and body of the package. I have applied the change to the UAT database
![image](https://cloud.githubusercontent.com/assets/5666297/12396273/7aa360ee-bdd4-11e5-8da7-6eb07d631a29.png)

****** Please see the 2 script files below ******

[sys_functions_pkg_body.txt](https://github.com/GCSO2/D3S-QUOTE/files/94658/sys_functions_pkg_body.txt)
[sys_functions_pkg_specs.txt](https://github.com/GCSO2/D3S-QUOTE/files/94659/sys_functions_pkg_specs.txt)

**Comment by giovanicani** [comment]
Note that the audit trigger of the quote tables should be updated. Eventually we will have to do this on all audit triggers, but for now, let's do it only on the quote triggers to test.

from:
```sql
   IF inserting THEN
      IF :new.ten_id IS NULL THEN 
         :new.ten_id := oraseq.nextval;
      END IF;
      :new.create_date := systimestamp;
      :new.create_user := user;
   ELSE
      :new.last_update_date := systimestamp;
      :new.last_update_user := user;
   END IF;
```

to:

```sql
   IF inserting THEN
      IF :new.ten_id IS NULL THEN 
         :new.ten_id := oraseq.nextval;
      END IF;
      :new.create_date := systimestamp;
      :new.create_user := NVL(system_functions_pkg.get_context_value('user_user_name'),user);
   ELSE
      :new.last_update_date := systimestamp;
      :new.last_update_user := NVL(system_functions_pkg.get_context_value('user_user_name'),user);
   END IF;
```

**Comment by d3sqa** [comment]
We are working on it

**Comment by d3sqa** [comment]
Audit log has been done through context variables at mobile end.
Work in progress on cloud side

**Comment by giovanicani** [comment]
Discuss this tomorrow.

**Comment by d3sqa** [comment]
Audit log through context variables is done at cloud. Testing is in progress

**Comment by giovanicani** [comment]
Meeting on Monday to review code.

**Comment by giovanicani** [comment]
Reviewed the code with the team. After going through the code and doing testing we found out that the first time the Quote opens it does have the correct context variable, but after saving the session ID changes and the username context variable goes back to 4-master.

Need to understand why 4-master which is a totally different application user is being set.

As discussed, everytime a new db session opens, it need to first set the context variable, then right after, do the SELECT, INSERT, DELETE or UPDATE statement.

Will meet again tomorrow at 7:30 to review findings.

**Comment by giovanicani** [comment]
Met on Tuesday, dev team found a way to fix the issue by setting the context variable before every update, insert, or delete.

Will meet again tomorrow, wednesday, at 7:30 to review findings.

**Comment by d3sqa** [comment]
Context variable issue is now fixed. Ready for testing in UAT

**Comment by giovanicani** [comment]
Works, THANKS for all hard work on this issue.
