### ISSUE TITLE
Cloud: Create RO from quote still not stable

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#53]
Selected the 3 labour lines below, a RO was created for only 2 of them, no idea why ?

Also, selected GPS-Battery and tried to add to RO button was not enabled. This screen is not stable, need improvement.

![image](https://cloud.githubusercontent.com/assets/5666297/12153860/528191ce-b48a-11e5-9710-fc6dc8f4f335.png)

**Comment by d3sqa** [comment]
We are looking to the labours being missed while creating RO from quote.

As for the GPS-Battery issue, kindly drag it and drop it in the 2nd grid. Then select the labour from left grid with RO. Only then will the 'Add To RO' button be enabled. See below screenshot

![image](https://cloud.githubusercontent.com/assets/13255706/12162269/53db5e6e-b521-11e5-8ff4-f7b52570b7a7.png)

**Comment by giovanicani** [comment]
I will wait this screen to be fully stable before I can re-test. Please consider this as a priority item.

**Comment by giovanicani** [comment]
Please make sure that the D&D is working smoother

**Comment by giovanicani** [comment]
please provide update on this one as well.

**Comment by giovanicani** [comment]
Buttons will be added instead of D&D.

4 buttons:

Left >>
<< Right
All >>
<< All

**Comment by giovanicani** [comment]
Looking better now... will review tomorrow with the team.

**Comment by d3sqa** [comment]
New drag and drop feature has been implemented. See screenshots:

![image](https://cloud.githubusercontent.com/assets/13255706/12321387/96bb9aba-bacf-11e5-8660-b1ed99c610f6.png)

Following tests are carried out:

1. The drag and drop button functionality works fine. 
Right > (Used to move one labour to the right grid at a time)
All >> (Used to move all labours to the right grid at once)
Left > (Used to move one labour to the left grid at a time)
All >> (Used to move all labours to the left grid at once)

2. When >> is clicked, only the labours against which RO is not created will be moved

2. Nearly 12 labours were added along with parts (min 2, max 5). Atleast 5 Labours were moved to the right grid and RO was created. The labours along with all the relevant parts reflected at the RO form.

3. Remove RO link button is tested and is functional i.e. the link successfully removes. Check screenshot below:

![1222222](https://cloud.githubusercontent.com/assets/13255706/12321523/4205e8d0-bad0-11e5-9910-23e257fe95b6.png)

4. The Add to RO button will remain disabled unless labour is selected first

5. Add to RO functionality is done

6. 12 Labours when moved simultaneously and created RO against it misses no labour. No repitition occurs and all the parts remain intact.

7. The Charge Hrs against part reflects at the 'Unit Charge' column at parts grid [RO]. The parts QTY reflects at 'Estimate', 'Actual' and 'Charge' columns at part's grid [RO].

![433333333](https://cloud.githubusercontent.com/assets/13255706/12322514/8db5222c-bad6-11e5-88b0-4d5783034292.png)

8. Labour grid mapping at RO labour grid:

- Quote Hours mapped to 'Charge' and 'Estimate'
- Std Hours mapped to 'Actual'

![3232323](https://cloud.githubusercontent.com/assets/13255706/12322622/0e9a30a8-bad7-11e5-8948-0efc4482b250.png)

9. All the relevant notes are displayed at the RO form against Labour and Parts

Ready to test at development environment

**Comment by giovanicani** [comment]
working. Closed.
