### ISSUE TITLE
Cloud: Workflow rules

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#54]
1 - If no checkbox is checked, then the status of the RO is STARTED;
2 - Quote cannot be internally approved (trailer and or reefer) WAITING ON VENDOR is checked;
3 - Quote cannot be sent to customer approval if not internally approved (trailer and or reefer) is not checked;
3.1 - When sent for customer approval is checked, popup email window to preview / send quote.
4 - Approved by customer and approved internally are mutually exclusive. Both of them cannot be checked at the same time. Reference and By are respectively required ( ***make it a popup, stored on audit log***)

5 - "MRO Reviewed against quote..." can only be checked if one of the 2 customer approvals (internal or by customer) is checked

6 - CLOSED can be checked at any point. Only users or groups with a certain access (ALLOW_CLOSE_QUOTE) will be able to close a quote.
6.1 - Close notes are required, make it a popup and store on audit log.

Other rules:

a. MRO can only be created if "approved by customer, reference:[]" or "approved internally by: []" is checked.

b. If approved by customer or internally by... and a MRO has been created... then user cannot uncheck the approval boxes.

c. If Quote is for Trailer and Reefer, than it requires trailer and reefer internal approvals. If not, only the respective approval

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by giovanicani** [comment]
please provide a more recent update on this one. Last update was 4+ days ago.

ਧਨਵਾਦ

**Comment by d3sqa** [comment]
Above mentioned checks have been applied but discussion is required. We will be discussing it in the upcoming meeting

**Comment by giovanicani** [comment]
Change the records on rep_work_order_quote_statuses in order to match the workflow descriptions (this may break the dashboard, but its OK for now)

Create new table that will store the statuses assigned to a quote and any notes specific to that status. (audit log still needs to be updated with the notes, in case a status notes is changes throughout the quote life cycle)

When clicking sent for customer approval, popup email to send to customer.

When clicking on the check boxes that require notes, user **must** enter notes. If cancel on the popup box is clicked then check box should be unchecked.

**Comment by giovanicani** [comment]
Giovani to add details on the main status of the Quote based on the flags set on the Workflow tab.

**Comment by giovanicani** [comment]
As discussed in the meeting, here are the status for the Quote, based on the workflow check boxes.

![image](https://cloud.githubusercontent.com/assets/5666297/12269187/206c9e52-b91e-11e5-9cc5-6ce8a79a951f.png)

WORKFLOW: Nothing checked 
QUOTE STATUS: **QUOTE STARTED**
BACKGROUND COLOR: Pale Purple (#d4c5f9)

WORKFLOW: Waiting on Vendor checked
QUOTE STATUS: **WAITING ON VENDOR**
BACKGROUND COLOR: Yellow (#fbca04)

WORKFLOW: If REEFER checked at the top, but REEFER not approved
QUOTE STATUS: **TCL REEFER APPRVL PENDING**
BACKGROUND COLOR: Orange (#eb6420)

WORKFLOW: If TRAILER checked at the top, but TRAILER not approved
QUOTE STATUS: **TCL TRAILER APPRVL PENDING**
BACKGROUND COLOR: Orange (#eb6420)

WORKFLOW: If all required approvals done, and sent to customer not checked
QUOTE STATUS: **SEND TO CUST. PENDING**
BACKGROUND COLOR: Red (#fc2929)

WORKFLOW: If sent to customer is checked AND not approved (by customer or internally) AND quote date is greater than current day - 30:
QUOTE STATUS: **CUST. APPRVL PENDING**
BACKGROUND COLOR: Yellow (#fbca04)

WORKFLOW: If sent to customer is checked AND not approved (by customer or internally) AND quote date is lower than current day - 30:
QUOTE STATUS: **CUST. APPRVL PENDING - OVERDUE**
BACKGROUND COLOR: Red (#fc2929)

WORKFLOW: If quote approved (by customer or internally), and "MRO Reviewed against Quote..." not checked
QUOTE STATUS: **MRO REVIEW AGAINST QUOTE PENDING**
BACKGROUND COLOR: Orange (#eb6420)

WORKFLOW: If "MRO Reviewed against Quote..." is checked
QUOTE STATUS: **BILL AS PER QUOTE PENDING**
BACKGROUND COLOR: Pale Green (#bfe5bf)

WORKFLOW: If Closed is checked
QUOTE STATUS: **CLOSED**
BACKGROUND COLOR: Blue (#207de5)

No changes are allowed to a closed Quote. Users can un-check the closed checkbox. Only users with permission mentioned above can close quotes.

Colors are suggestions only, will finalize once we see how they work with the workflow

Note that these are going to be the same status shown on the dashboard. except the CLOSED, Closed Quotes will not be in the dashboard.

**Comment by d3sqa** [comment]
@giovanicani, we have a question here:

Currently, we are allowing simultaneous checking of the following checkboxes:

![image](https://cloud.githubusercontent.com/assets/13255706/12284933/75038328-b9d6-11e5-9ac3-8d4976083331.png)

What would be the Quote Status in this case ? Can you please give us a feedback on this ?

**Comment by giovanicani** [comment]
Yes, this is possible. when there is a need for approval on Reefer and TRailer. (both check box at the top are checked)

WORKFLOW: If all required approvals done, and sent to customer not checked
QUOTE STATUS: **SEND TO CUST. PENDING**
BACKGROUND COLOR: Red (#fc2929)

@d3sqa Please let me know if this is clear. Thanks.

**Comment by giovanicani** [comment]
Update on this status: **CUST. APPRVL PENDING - OVERDUE** and  **CUST. APPRVL PENDING**


WORKFLOW: If sent to customer is checked AND not approved (by customer or internally) AND quote date is greater than Expiry Date (new field requested on #60 )
QUOTE STATUS: **CUST. APPRVL PENDING - OVERDUE**
BACKGROUND COLOR: Red (#fc2929)

WORKFLOW: If sent to customer is checked AND not approved (by customer or internally) AND quote date is less than Expiry Date (new field requested on #60 )
QUOTE STATUS: **CUST. APPRVL PENDING**
BACKGROUND COLOR: Yellow (#fbca04)

**Comment by d3sqa** [comment]
Following activities has been done:

- Statuses are populated dynamically
- Notes are now saving against statuses. Work in progress on checking unchecking feature

Work in progress:

- Logging activities in audit log
- Quotes status updation

**Comment by giovanicani** [comment]
thanks for the update. Will further check when the 2 outstanding items are done.

**Comment by d3sqa** [comment]
Work done on Quote's status updation:

- WORKFLOW: Nothing checked 

![image](https://cloud.githubusercontent.com/assets/13255706/12417351/57499104-bec9-11e5-92d6-cfa7774a7e3c.png)

- WORKFLOW: Waiting on Vendor checked

![screenshot_40](https://cloud.githubusercontent.com/assets/13255706/12417288/d1c1e216-bec8-11e5-88e6-a7ae76f137f3.png)

- WORKFLOW: If REEFER checked at the top, but REEFER not approved

![screenshot_41](https://cloud.githubusercontent.com/assets/13255706/12417398/af3f2cd4-bec9-11e5-9e40-3a308a0a0f96.png)

- WORKFLOW: If TRAILER checked at the top, but TRAILER not approved

![screenshot_42](https://cloud.githubusercontent.com/assets/13255706/12417430/e24c83b0-bec9-11e5-9655-71859f178793.png)

- WORKFLOW: If all required approvals done, and sent to customer not checked

![screenshot_43](https://cloud.githubusercontent.com/assets/13255706/12417501/58eee0ee-beca-11e5-9d53-e223ba50c701.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12417553/aa726e4a-beca-11e5-9120-fb04ed55b547.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12417564/ba80329a-beca-11e5-9be0-32fee78dedd5.png)

- WORKFLOW: If sent to customer is checked AND not approved (by customer or internally) AND quote date is greater than Expiry day - 30:

![screenshot_44](https://cloud.githubusercontent.com/assets/13255706/12417679/8642b3e4-becb-11e5-92f4-a56b95b2851a.png)

- WORKFLOW: If sent to customer is checked AND not approved (by customer or internally) AND quote date is lower than current day - 30:

![screenshot_45](https://cloud.githubusercontent.com/assets/13255706/12417751/1e7a192c-becc-11e5-8567-2b204145e327.png)

- WORKFLOW: If quote approved (by customer or internally), and "MRO Reviewed against Quote..." not checked

![image](https://cloud.githubusercontent.com/assets/13255706/12417869/fe549de2-becc-11e5-93e7-fc33a5dc2389.png)

- WORKFLOW: If "MRO Reviewed against Quote..." is checked

![image](https://cloud.githubusercontent.com/assets/13255706/12417922/73231e8c-becd-11e5-8351-32ccd6226bc0.png)

- WORKFLOW: If Closed is checked

![image](https://cloud.githubusercontent.com/assets/13255706/12417943/9759c72e-becd-11e5-9f91-6cd6a4682923.png)

Work in progress on the following:

- Audit Log
- Un checking and reverting the statuses due to it

**Comment by d3ssupport** [comment]
Done on audit log for quote status changing. QA testing pending.

**Comment by giovanicani** [comment]
After creating an Quote, entering labour and parts, approving internally and saving, got an incorrect line on the audit log saying that the expire date was changed, however it wasn't, see screen shot below:

![image](https://cloud.githubusercontent.com/assets/5666297/12418953/cd2f7ed6-be80-11e5-8b09-c2ee4c1790dd.png)

For reference, quote number was: Q001604

**Comment by giovanicani** [comment]
When checking the box below for the first time.

![image](https://cloud.githubusercontent.com/assets/5666297/12418978/fd76908e-be80-11e5-8c5b-75e701f86c1e.png)

The program should ask if user wants to send email to customer (pop-up). If user selects : YES - then show email window, if user selects NO - close popup, but still leave the check box checked.

**Comment by giovanicani** [comment]
**Do not send the email automatically**, when the RE-SEND button is checked, only popup the email box when the re-send is checked, so that user can add text to the email and send.

![image](https://cloud.githubusercontent.com/assets/5666297/12419047/8bf237be-be81-11e5-970e-f25f2a982b08.png)

**Comment by giovanicani** [comment]
Message below should not exit. It should still popup the email box for users to enter address and send.

![image](https://cloud.githubusercontent.com/assets/5666297/12419067/b545a768-be81-11e5-881b-ecfa827ee020.png)

**Comment by d3ssupport** [comment]
When checking the box below for the first time.

![image](https://cloud.githubusercontent.com/assets/5666297/12418978/fd76908e-be80-11e5-8c5b-75e701f86c1e.png)

The program now  show pop-up email window. If user selects NO - close popup, check box will remain checked.

**Comment by d3ssupport** [comment]
Now stopped sending email automatically.when the RE-SEND button is checked, popup the email box is displaying now. If no email found for current customer then still popup the email box is displaying

Also audit log done,
 
![image](https://cloud.githubusercontent.com/assets/13255682/12448669/77ee3fc4-bf99-11e5-99a9-8203175cc363.png)

**Comment by giovanicani** [comment]
On Audit log 2 issues:

1 Make sure that the user that did the change is tracked under the USER column

2 On the verbiage when the workflow is checked or unchecked, follow the examples below:

MRO REVIEWED AGAINST QUOTE, READY FOR BILLING was checked
WAITING ON VENDOR was unchecked
...

**Comment by giovanicani** [comment]
All seems to be working, only item missing is : **ALLOW_CLOSE_QUOTE** . Work in progress.

**Comment by giovanicani** [comment]
:+1

**Comment by d3sqa** [comment]
Close feature is now available for specific users only. Not every user can close the quote. Ready for testing in development environment

**Comment by giovanicani** [comment]
Giovani to test.

**Comment by giovanicani** [comment]
verified.
