### ISSUE TITLE
Cloud: Create RO & Status

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#56]
On the grid, only have the RO link to open a new tab with the respective RO. Remove the click event from any other column (ie... date, status, etc...)

**Comment by giovanicani** [comment]
As discussed and shown during last dev meeting.

**Comment by d3sqa** [comment]
At the RO(s) & Status grid, only the RO # column is clickable now. Rest of the columns are disabled. Ready to test in development environment

**Comment by giovanicani** [comment]
Thanks will test

--
Giovani Cani

**Comment by giovanicani** [comment]
works. closing this one.
