### ISSUE TITLE
Cloud: Add filters on the QUOTE and MRO LIST screens.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#57]
Please add the following filters:

**Quote Listing:**

Part #: Drop down list searchable by all parts (not only active). Search by part desc and or part number
Labour (Sys-Asy): Search by system and assembly codes.

**MRO Listing:**

Customer: Same as was done on the quote listing
Part #: Drop down list searchable by all parts (not only active). Search by part desc and or part number
Labour (Sys-Asy): Search by system and assembly codes.

**Comment by giovanicani** [comment]
I see that some work is being done here... kindly make sure that the filter list is sorted on the labour codes. (Sys-Asy), thanks!

**Comment by d3ssupport** [comment]
Done Please ready to test in development environment.

**Comment by giovanicani** [comment]
This was done on the Quote, but not in the MRO. Please see request at the top of this issue. Needs to be done on the MRO as well. **See details at the top**

**Comment by d3ssupport** [comment]
Yes in MRO these filters need to apply, we just applied in quote.

**Comment by d3sqa** [comment]
Work in progress on implementing same filter at MRO screen

**Comment by d3ssupport** [comment]
Listing has implemented, Now can search on (Sys-Asy) and Part #:
Still some tweaking renaming so work on progress on it.

**Comment by giovanicani** [comment]
Tomorrow we will be done with this.

**Comment by d3sqa** [comment]
Filter based on Sys-Asy and parts has been implemented on MRO Listing screen as well. Ready to test in development environment

**Comment by giovanicani** [comment]
WORKS, however found a bug on the date, will create a new issue.
