### ISSUE TITLE
Cloud / Report: Change Quote Expiry from 60 to 30

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#58]
Hi, as per management direction, please change the expiry of a quote from 60 to 30.

Change below:
![image](https://cloud.githubusercontent.com/assets/5666297/12239226/ac6c18e8-b855-11e5-9d06-24fa9df65bad.png)

Change Report:
![image](https://cloud.githubusercontent.com/assets/5666297/12239240/bc27aaea-b855-11e5-9863-b1d001116422.png)

Thanks!

**Comment by d3sqa** [comment]
Expiry of quotes has been changed to 30 days. See below screenshots:

![image](https://cloud.githubusercontent.com/assets/13255706/12254935/37336796-b910-11e5-9f69-5e7c87acf9f0.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12254937/3cabeebe-b910-11e5-9f93-4ccc2da9dfd2.png)

**Comment by giovanicani** [comment]
thanks!
