### ISSUE TITLE
Cloud: Quote Listing Search, change emptyText verbiage

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#59]
Make it like on the MRO, change "Search" to "Quick Search (Quote #, Preferred #)"

![image](https://cloud.githubusercontent.com/assets/5666297/12264691/7667c678-b906-11e5-9504-798495f5d55c.png)

**Comment by d3sqa** [comment]
Verbiage has been added. Please see below screenshot:

![image](https://cloud.githubusercontent.com/assets/13255706/12286463/f7716582-b9e5-11e5-8626-07e6d085b60b.png)

**Comment by giovanicani** [comment]
thanks!
