### ISSUE TITLE
Cloud: Prepopulate customer owner or last lease / rental customer

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#6]
Like it is done on the mobile, when the unit is selected:

If trailcon unit, prepopulate with last rental / lease returned customer .
If not trailcon unit, prepopulate with the owner of the trailer.

**Use same logic from mobile.**

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The last RTMI customer or the trailer owner according to the provided preferred # are successfully populating in the respective fields. The fix is available at the development environment and will be available at UAT once the latest release is deployed there

**Comment by giovanicani** [comment]
will test and provide update.

**Comment by giovanicani** [comment]
tested, works ok.
