### ISSUE TITLE
Cloud: Add new field Called Expiry Date on Quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#60]
Perhaps on the same line, after the Quote date.

The Expiry Date, if blank will be auto populated with Quote Date plus 30 days. After being filled will not auto change unless user changes it.

Track changes on the audit log.

EXpiry date cannot be more than 60 days from Quote Date.

Change report to read Expiry Date from this new field.

**Comment by d3sqa** [comment]
The expiry date field has been incorporated at Update Quote form for now and activity is also logged at audit log:

![image](https://cloud.githubusercontent.com/assets/13255706/12323621/cce568aa-bade-11e5-882a-fe8222806946.png)

Expiry date has also been made dynamic at customer report.

Please note that Expiry date at Create form and validation checks are not applied yet. Work in progress on that.

**Comment by giovanicani** [comment]
thanks for the update.

**Comment by giovanicani** [comment]
As per meeting:

Expiry doesn't require time component.

On create form, make it Location / Assigned To on the same line, and add the expiry field under the Quote Date / Time.

**Comment by d3ssupport** [comment]
On create Quote form expiry date field has been added and time component has also removed and date is saving.
![image](https://cloud.githubusercontent.com/assets/13255682/12352891/be01883c-bbab-11e5-892a-920c90bce5ea.png)
Still some tweaking remaining on update form so work on progress on it.

**Comment by giovanicani** [comment]
ok, thanks for the update. Let me know when it is done so I will do the full testing.

**Comment by d3sqa** [comment]
The expiry date is incorporated at update quote form as well. 
Please note that there is a timezone based conversion applied at the date field which results in the conversion of the date. However, at the audit log, the date will reflect same as the one given by the user.

**Comment by giovanicani** [comment]
good. works! Thanks!
