### ISSUE TITLE
Cloud & Mobile: Add new Hour Field

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#62]
It was decided that we will need to track the estimated hours by mechanics. The estimated hours, may not be the same as the quoted hours.

Please add the field estimate hours on the quote labour table. It should be the same type as the quoted hours, with the following characteristics:

**Cloud**
Main screen:
![image](https://cloud.githubusercontent.com/assets/5666297/12336405/6b87e2f6-bad2-11e5-8ae8-430fb7d41da3.png)

Selection popup:
![image](https://cloud.githubusercontent.com/assets/5666297/12336411/7a9e07b6-bad2-11e5-819f-0ce742e49d35.png)

**When creating MRO from QUOTE, populate:
MRO Charge & Actual with QUOTE Estimated Hours**

***Do not use the column ESTIMATE_HOURS from the REP_WORK_ORDER_LABOUR table, this column will be dropped in the near future***

![image](https://cloud.githubusercontent.com/assets/5666297/12337150/594a5232-bad6-11e5-93b9-315f4c3e28a4.png)

**Mobile**
Note that quoted hours will no longer be available on the Mobile. Quoted will only appear in the cloud.

Main Screen:
![image](https://cloud.githubusercontent.com/assets/5666297/12336440/a5b04752-bad2-11e5-8da3-0d20a69cb9e4.png)

Selection Box:
![image](https://cloud.githubusercontent.com/assets/5666297/12336455/b91bdb30-bad2-11e5-88aa-55b644ee4618.png)

***Important - Applicable to Mobile and Cloud***
If standard hour is blank then estimate can be changed, if standard hour has value, then estimate will be the same as standard and cannot be changed.

****MRO Screen****

![image](https://cloud.githubusercontent.com/assets/5666297/12337442/20fdfabc-bad8-11e5-989e-897901d08e6e.png)

**Comment by giovanicani** [comment]
On the MRO the EST and Quote columns are READ ONLY.

**Comment by d3sqa** [comment]
CLOUD - Estimate Hours has been added at the Labour grid as well as on labour pop up window:

![screenshot_29](https://cloud.githubusercontent.com/assets/13255706/12389536/38f0437a-bdfb-11e5-8c67-0c8d91cf23ef.png)

![screenshot_30](https://cloud.githubusercontent.com/assets/13255706/12389540/40cf3bbe-bdfb-11e5-9834-046c63ddcbd2.png)

- Quote Estimated Hours are now mapped to Charge and Actual columns at RO

![screenshot_31](https://cloud.githubusercontent.com/assets/13255706/12390132/432e6048-bdff-11e5-8bfd-a403a7081685.png)

- If the standard hours is blank, estimate field can be changed. See screenshot:

![screenshot_33](https://cloud.githubusercontent.com/assets/13255706/12390218/ee6a12f4-bdff-11e5-97ff-324aa47a8230.png)

- If the Standard Hours has a value, then Estimate will be populated with the same value and will be read only

![screenshot_34](https://cloud.githubusercontent.com/assets/13255706/12390279/4806f3a4-be00-11e5-98ad-4c802969807d.png)

MOBILE - Estimate hour at Quotes:

![screenshot_39](https://cloud.githubusercontent.com/assets/13255706/12414700/1d468436-beb9-11e5-9423-22319932e143.png)
The data also reflects on cloud

Work in progress on the following:

- Quote - Mobile (Handling of labour when added from cloud, it is currently causes error while closing Quote)
- Handling of Estimate hours at RO - Mobile
- Populating Estimate and Quote columns at the RO form via the above mentioned fields

**Comment by giovanicani** [comment]
work in progress.

**Comment by d3sqa** [comment]
1. Labours handling is done when added from cloud. Quote is now successfully closed. 

2. Estimate hours functionality is done at RO mobile i.e. when RO is created from quote and then resumed at mobile, the estimated hrs reflects there. When changed will then reflect at cloud at Actual and Charge Hrs.

3. Estimated and Quote columns are now populated when RO is created from quote

Ready to test in development environment

**Comment by giovanicani** [comment]
Giovani to Test.

**Comment by giovanicani** [comment]
works well. Found some bugs when closing MRO, but this will be tracked on a separate issue.
