### ISSUE TITLE
Cloud: Date Filter not working and not standard format being used, see image.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#63]
See image below, date filter not working. Also make sure that the standard format is used.

**Please test the filter with a combination of date, customer, labour, parts, etc....**

![image](https://cloud.githubusercontent.com/assets/5666297/12354961/84abb538-bb67-11e5-8438-98d08331de67.png)

***Same issues happens on MRO filter, please fix that too***

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3ssupport** [comment]
Done at Quotes.. Work in progress in MRO.

**Comment by giovanicani** [comment]
Filter on Quote seems to be working. However RESET is not.

RESET - Reset all the filters with the same value when the Quote Listing is opened, and refresh data on the grid.

This is not happening right now. Please fix and I will re-check.

**Comment by d3sqa** [comment]
Date format has been changed to MM/DD/YYYY. Also, the date filter has been made functional at MRO Filter. See screenshot below:

![screenshot_37](https://cloud.githubusercontent.com/assets/13255706/12414257/27bd84c6-beb6-11e5-9afb-2ee14d06d266.png)

With multiple parameters:

![image](https://cloud.githubusercontent.com/assets/13255706/12414298/80728a80-beb6-11e5-88cb-f7f7ed2c0079.png)


Reset functionality at Quote Listing is working now. The filter values are reset to blank and all the data is retrieved at the listing grid

**Comment by giovanicani** [comment]
Format is good
Reset is good (Not assigned cb will be moved to quick filter)
Only issue is the date filter, records not matching filter range (see more details on #66)

**Comment by d3sqa** [comment]
Date filter is now functional at MRO Listing. 

![image](https://cloud.githubusercontent.com/assets/13255706/12446944/ec586886-bf8e-11e5-9fa0-9752fcaf5eb9.png)

Ready to test in development environment

**Comment by giovanicani** [comment]
works!
