### ISSUE TITLE
Cloud: Filter layout adjustments

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#64]
On the box below, please do the following changes:

1 Change "Preferred #" to "Preferred (Trailer #)", **make the same change on the MRO Filter**
2 Change "Location" to "Branch" (also change in the Quote Detail Screen)
3 Sequence should be: **make same sequence adjustments in the MRO Filter**
Customer
Preferred (Trailer #)
Unit #

![image](https://cloud.githubusercontent.com/assets/5666297/12355856/7d488ff4-bb6d-11e5-9d37-e2472569e022.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Layout Adjustments have been done at Quote and MRO filters:

- Sequence has been updated to Customer > Preferred (Trailer #) and then Unit #
- Location has been renamed to 'Branch' (Both at filter window and on the Quote detail forms)
- Preferred # has been renamed to Preferred (Trailer #)

See below screenshots:

Quote Filter:

![image](https://cloud.githubusercontent.com/assets/13255706/12385419/bf7da2b6-bddd-11e5-8439-97f8beb0272f.png)

MRO Filter and date format:

![image](https://cloud.githubusercontent.com/assets/13255706/12390867/7710d2dc-be05-11e5-86ff-25b264f2ded9.png)

Work in progress - Date filtering at MRO 

At Add Quote form:

![image](https://cloud.githubusercontent.com/assets/13255706/12385533/ec516ab0-bdde-11e5-8215-aa0a47a2cdd5.png)

At Update Quote form:

![image](https://cloud.githubusercontent.com/assets/13255706/12385503/91ba305a-bdde-11e5-99ba-d8838d4b94bd.png)

**Comment by giovanicani** [comment]
good. thanks!

**Comment by d3sqa** [comment]
The date filter has been made functional at MRO Filter. See screenshot below:

![screenshot_37](https://cloud.githubusercontent.com/assets/13255706/12414257/27bd84c6-beb6-11e5-9afb-2ee14d06d266.png)
