### ISSUE TITLE
Cloud: Dashboard Columns re-arrangement

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#65]
![image](https://cloud.githubusercontent.com/assets/5666297/12356477/ed216ab4-bb70-11e5-959c-0b100e881038.png)

Hi Please change the sequence and label of columns for ***all status*** as below:
Please make sure that the width is properly sized for each column contents.

Quote #
Age (Days)
Brief Description
Quote Date
Expiry Date
Customer
Preferred (Trailer #)
Assigned To

--

Remove Reference #
Remove Unit #

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The columns at Quote Dashboard has been re-arranged. Please see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12383649/47a515f2-bdca-11e5-845f-e95dc6a47fc1.png)

If Location/Status column needs to be removed too, please let us know.

**Comment by d3sqa** [comment]
The columns at Quote Dashboard has been re-arranged. Please see the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12383684/d283ce16-bdca-11e5-8561-51a3cad02091.png)

If Location/Status column needs to be removed too, please let us know.

**Comment by giovanicani** [comment]
this is good. thanks.
