### ISSUE TITLE
Cloud: MRO Status when created from Quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#66]
Please see below the instruction for status when MRO is created from Quote

**User should also be able to assign MRO to a mechanic**

![image](https://cloud.githubusercontent.com/assets/5666297/12359771/12b439da-bb82-11e5-8fad-4bd9faf20d1e.png)

**Comment by d3sqa** [comment]
Following points have been incorporated. Work in progress on the rest of functionality:

- When the RO is created from Quote, not voided, not assigned and not completed, the status will be Not Assigned. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12388050/5567bc4e-bdf2-11e5-9a13-9b52540a5deb.png)

- Estimate Flag has been removed from RO form. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12388091/87704ff8-bdf2-11e5-8f4a-7c0810e8d761.png)

- Legends has been added to the RO Listing. Please see screenshot below:

![screenshot_28](https://cloud.githubusercontent.com/assets/13255706/12388637/c6430786-bdf5-11e5-8f54-066f474f7d25.png)

Please note that the status color codes are tentative and will be changed upon suggestion.

**Comment by giovanicani** [comment]
Will test, can you please do 2 small changes - verbiage ONLY:

1 Remove the Estimate legend
2 Change the "Completed & Approved"  legend to "Sending to EMDECS"

Thanks!

**Comment by giovanicani** [comment]
work in progress.

**Comment by d3sqa** [comment]
Tweaks have been done. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12411014/58166260-be9c-11e5-9fee-44664ca659a5.png)

**Comment by d3sqa** [comment]
Not Assigned checkbox has been added to the MRO filter. See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12415231/5be95846-bebc-11e5-85b0-cbe0644f6ebc.png)

Search with multiple parameters including 'Not Assigned' checked:

![image](https://cloud.githubusercontent.com/assets/13255706/12417007/db391000-bec6-11e5-8663-9a345b4548a7.png)

Please check in development environment

**Comment by giovanicani** [comment]
As per meeting, please move Not Assigned to quick filter section, just before Work In Progress Check Box.

As seen, there is an issue with the date filter. Need to first convert the records to user TZ then truncate and compare with the date filter range.

**Comment by d3sqa** [comment]
Not Assigned checkbox has been added to the Quick Filter.

![image](https://cloud.githubusercontent.com/assets/13255706/12446899/a34b3100-bf8e-11e5-940b-00df401fbeaf.png)

Date filter is now functional at MRO Listing screen.
Ready to test in development environment

**Comment by giovanicani** [comment]
Looks good on the first testing, will do another check and if all good then close ticket.

**Comment by giovanicani** [comment]
works!
