### ISSUE TITLE
Cloud: Provide user feedback when email added to the to,cc,bcc from contact list

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#67]
As discussed.

![image](https://cloud.githubusercontent.com/assets/5666297/12449232/debf00b2-bf49-11e5-8897-b9c9f97af56d.png)

**Comment by d3sqa** [comment]
A feedback message has been added during addition of emails from contact list.

![image](https://cloud.githubusercontent.com/assets/13255706/12473562/025658d6-c035-11e5-9dc0-b271c4e705b7.png)

**Comment by giovanicani** [comment]
okay this is done.
