### ISSUE TITLE
Cloud: Dashboard add filter for Branch

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#69]
Please add a filter by branch on the dashboard screen. The default value should be the users branch.

As mentioned on the screen below... a reference should be added on the filter popup informing the user that the apply filter is only applicable to the quote listing screen.

![image](https://cloud.githubusercontent.com/assets/5666297/12450455/d2f6e4ae-bf51-11e5-823a-5b42cbc7fdbd.png)

**Comment by d3sqa** [comment]
The filter functionality is done.

Work in progress on the following:
1. Records 'Count' updation at Quote Dashboard
2. Filtering through the User branch

**Comment by d3sqa** [comment]
Implementation done as per discussion. Ready to test in development environment

**Comment by giovanicani** [comment]
Giovani to verify.

**Comment by giovanicani** [comment]
works!
