### ISSUE TITLE
Cloud: Quote report not showing part's charge, showing 0.00

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#70]
See report below, parts charge is ZERO on the report.

**Also check why shop supply is zero.**

![image](https://cloud.githubusercontent.com/assets/5666297/12484460/6bbcfd1e-c028-11e5-959b-5e323b4c8ca5.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Parts Charge is now displayed at the report. Please see below screenshot:

![12122222222222](https://cloud.githubusercontent.com/assets/13255706/12508069/9bbf8326-c11b-11e5-96ee-d31f18be46ab.png)

**Comment by d3sqa** [comment]
Report screenshot for Quote # 1679:

![image](https://cloud.githubusercontent.com/assets/13255706/12508179/53e39ba4-c11c-11e5-91a8-f24c00edb847.png)

**Comment by giovanicani** [comment]
verified.
