### ISSUE TITLE
Cloud: Incorrectly showing Cust. Approval Pending OVERDUE

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#71]
See screen shot below... expire date is February 21, however the status is OVERDUE.

It should be only overdue, if actual date is greater than expire date.

![image](https://cloud.githubusercontent.com/assets/5666297/12484667/596d5928-c029-11e5-9bdd-558069c6c75b.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by giovanicani** [comment]
Done, Giovani to test.

**Comment by giovanicani** [comment]
works, however found issue with timezone, will open another ticket.
