### ISSUE TITLE
Cloud: Change emptyText property

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#72]
... on the box below to:

"Enter information that can be referenced as the customer approval, i.e.: Approver's name, special remarks, etc..."
![image](https://cloud.githubusercontent.com/assets/5666297/12484735/a8cdd448-c029-11e5-9fac-f0bdab93817c.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Place holder has been updated with the given text verbiage. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12503680/60614ce2-c0f8-11e5-9b51-24ed0f168933.png)

**Comment by giovanicani** [comment]
verified.
