### ISSUE TITLE
Mobile: Replace Estimate References to Quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#73]
On MRO in progress TAB, please change last column "Est" to Quote #.

Thanks!
![image](https://cloud.githubusercontent.com/assets/5666297/12485215/c72c080e-c02b-11e5-965f-4234995ec4ea.png)

**Comment by giovanicani** [comment]
On the MRO detail, please remove the estimate check box and add the Quote # info.

![image](https://cloud.githubusercontent.com/assets/5666297/12485329/49a4f1a6-c02c-11e5-88e7-474a3dda7752.png)

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by d3sqa** [comment]
Done. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/12509889/b7758f1e-c127-11e5-9051-2bb02958ea12.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12509899/bde71412-c127-11e5-8da4-dc0d22a75db8.png)

**Comment by giovanicani** [comment]
verified.
