### ISSUE TITLE
Mobile: When completing an MRO created from Quote getting the following error

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#74]
![image](https://cloud.githubusercontent.com/assets/5666297/12485486/fc9337a0-c02c-11e5-8c94-780b1ea0729b.png)

**Comment by d3ssupport** [comment]
Work in progress!

**Comment by d3sqa** [comment]
This issue has been fixed. The fix will be shipped in the upcoming mobile debug

**Comment by giovanicani** [comment]
Giovani to test.

**Comment by giovanicani** [comment]
works!
