### ISSUE TITLE
Mobile: When completing or holding MRO, validate that labour shift is entered in all labours

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#75]
When MROs are created from Quotes, they don't have the shift field filled in. Please make sure that when COMPLETING or HOLDING MRO, make sure that the mobile system checks that all labours have the shift field filled in, otherwise prompt message for the ser.

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by d3sqa** [comment]
Validation regarding labour shift has been done. The fix will be shipped in upcoming debug

**Comment by giovanicani** [comment]
Giovani to test.

**Comment by giovanicani** [comment]
works !
