### ISSUE TITLE
Cloud: Discrepancies between INSERT and UPDATE forms

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#76]
Once more I am finding discrepancies between INSERT and UPDATE forms.

- PO is in different spots, it should be under customer information tab.
- Reference # does not exist on INSERT form, but it does on UPDATE form.

**PLEASE MAKE SURE INSERT AND UPDATE FORMS ARE THE SAME**

**Comment by giovanicani** [comment]
Date format is wrong on INSERT FORM

**Comment by d3sqa** [comment]
Forms are now made same. Please see screenshot below:

![12assssss](https://cloud.githubusercontent.com/assets/13255706/12504517/ec3fbcf6-c0ff-11e5-9fb2-cc9ff456ef00.png)

**Comment by giovanicani** [comment]
verified.
