### ISSUE TITLE
Cloud: When MRO is created from Quote, copy PO into MRO

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#77]
When MRO is created from Quote, always copy the PO field content (if not null) into the new MRO or MROs created.

**Comment by d3sqa** [comment]
PO # is now copied at the MRO which is created from quote. Please see screenshot below:

![12333333](https://cloud.githubusercontent.com/assets/13255706/12503967/18012c08-c0fb-11e5-89f5-ac0a57fc51cd.png)

**Comment by giovanicani** [comment]
PO not the same ! Should be left exactly the same as it was entered on Quote.

**Comment by giovanicani** [comment]
DEv team to check and report back.

**Comment by d3sqa** [comment]
The PO # will reflect same at RO form as entered by user on Quote form. Ready to test in development environment

**Comment by giovanicani** [comment]
ok verified.
