### ISSUE TITLE
Cloud: Add warning if Quote not approved by customer, and MRO are being created

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#78]
![image](https://cloud.githubusercontent.com/assets/5666297/12487343/c7d94bd2-c034-11e5-90ad-8631add78c5f.png)

If none of the 2 boxes above are checked, and user is clicking on the create ROs from quote, please show the following message:

This quote is not in a Customer Approved Status, proceed with creating MRO ? YES / NO buttons.

YES - Opens the popup screen
NO - Does not open the popup screen

![image](https://cloud.githubusercontent.com/assets/5666297/12487363/dd32fe38-c034-11e5-8a85-4ba0b758e750.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Message has been displayed when above checkboxes remain unchecked and user proceeds with RO creation. See screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12504654/6dc81ec0-c101-11e5-828f-334bf2b37a14.png)

**Comment by giovanicani** [comment]
okay
