### ISSUE TITLE
Cloud: Add reference on the log, when MROs are created from Quote

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#79]
Currently there is no reference on the Audit Log that a MRO was created. Need MRO number, datestamp user, etc...

**Comment by d3sqa** [comment]
Reference has been added to both RO and Quote. Please see below screenshots:

At Quote:

![image](https://cloud.githubusercontent.com/assets/13255706/12503201/cacd1e44-c0f3-11e5-8267-5488fd8fe38c.png)

At RO:

![image](https://cloud.githubusercontent.com/assets/13255706/12503212/ed45096e-c0f3-11e5-9283-fe6629c9db42.png)

**Comment by giovanicani** [comment]
okay
