### ISSUE TITLE
Mobile: Change verbiage on inquiry frame

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#80]
See label below:

Change verbiage to "MRO - ASSIGNED / IN PROGRESS / HOLD"

![image](https://cloud.githubusercontent.com/assets/5666297/12487551/a88d110e-c035-11e5-8ab5-381cca3e27d9.png)

also change: COMPLETED to "MRO - COMPLETED"

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by d3sqa** [comment]
Verbiage has been changed. Change will be shipped in upcoming debug.
Please see screenshot below:

![wqwqwqwqwqwq](https://cloud.githubusercontent.com/assets/13255706/12508709/5f07a7fc-c11f-11e5-8190-6cbdcc5d66f8.png)

**Comment by giovanicani** [comment]
okay.
