### ISSUE TITLE
Mobile: Verification: As soon as a Quote is approved by Trailcon, changes on Mobile can no longer be saved

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#81]
If any of the boxes below are checked, when MOBILE saves the QUOTE, it should popup saying. 

"Quote is an status that no longer allows changes from the Mobile." OK

This is to avoid mobile changing quotes already approved sent to the customer, closed or voided.

![image](https://cloud.githubusercontent.com/assets/5666297/12487934/404f7328-c037-11e5-967a-c41a0b800a59.png)

![image](https://cloud.githubusercontent.com/assets/5666297/12487943/4668e032-c037-11e5-8397-7b8019ba3916.png)

**Comment by d3ssupport** [comment]
Work in Progress!

**Comment by d3sqa** [comment]
Done. A message is prompted in case of a quote being in one of the above statuses. Ready to test in development environment

**Comment by giovanicani** [comment]
Giovani to test, on UAT, when the mobile app is available.

**Comment by giovanicani** [comment]
works.!
