### ISSUE TITLE
Cloud: Remove the time component on the Expiry Date - Dashboard

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#82]
See below, please remove time component to keep things consistent.

![image](https://cloud.githubusercontent.com/assets/5666297/12514605/3659bc32-c0f2-11e5-9b26-ea6ad4109e82.png)

**Comment by d3sqa** [comment]
Time component has been removed from Expiry Date at Quote Dashboard screen. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12528825/c60391e0-c1c5-11e5-94d4-775f7bf689cf.png)

**Comment by giovanicani** [comment]
verified.
