### ISSUE TITLE
Cloud: TZ Issue

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#83]
Created Quote at 10:14 EST when saved and form reload went to 5:14

![image](https://cloud.githubusercontent.com/assets/5666297/12514690/916d571e-c0f2-11e5-91f0-8c610738555e.png)

**PLEASE REVIEW ALL DATES TO MAKE SURE THERE ARE NO TZ ISSUES - MOBILE AND CLOUD**

**Comment by d3sqa** [comment]
TZ issue has been resolved and ready to test in UAT environment

**Comment by giovanicani** [comment]
Issue has been resolved.
