### ISSUE TITLE
Cloud: Please align labour and part heading with content

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#85]
On numeric columns, content and headings should be right aligned. On date and text, both should be left aligned. See on picts below how they are not aligned at all.

![image](https://cloud.githubusercontent.com/assets/5666297/12558099/f4d570c8-c35b-11e5-9be6-3348523a7823.png)

![image](https://cloud.githubusercontent.com/assets/5666297/12558119/145c029a-c35c-11e5-9b01-fbd2b22f52a9.png)

**Comment by giovanicani** [comment]
Issue happens on the INSERT form, UPDATE seems to be OK.

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done at Labour's grid at Create Quote. Please see screenshot below (UAT):

![image](https://cloud.githubusercontent.com/assets/13255706/12642846/292a271c-c5da-11e5-824c-7625b6183a61.png)

Work in progress on Part's grid

**Comment by d3sqa** [comment]
Done at Parts Grid as well. Please check screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12669978/7eed646e-c686-11e5-8ea0-4d2276d0f1e7.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
works!
