### ISSUE TITLE
Cloud: Error when checking image available on customer report

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#86]
Having the following error when checking image available for customer report.

![image](https://cloud.githubusercontent.com/assets/5666297/12558249/a14cda44-c35c-11e5-8c34-eab4682bf5a3.png)

**Comment by giovanicani** [comment]
Not sure why this is happening, it was working last time I tested.

**Comment by d3sqa** [comment]
Images are now available at Customer Report. Please check in UAT Environment

**Comment by giovanicani** [comment]
resolved.
