### ISSUE TITLE
Cloud: Change label from Cancel to Close (red button)

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#88]
![image](https://cloud.githubusercontent.com/assets/5666297/12580687/8bd21582-c3ff-11e5-9332-fbd59c5209ff.png)

**Comment by d3ssupport** [comment]
Work in progress!

**Comment by d3ssupport** [comment]
Done. Ready for test in UAT,

![image](https://cloud.githubusercontent.com/assets/13255682/12613226/21979694-c51a-11e5-96e6-92ed788d4a0f.png)
