### ISSUE TITLE
Cloud: Remove tooltip on Quote Listing & Dashboard

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#89]
![image](https://cloud.githubusercontent.com/assets/5666297/12581576/88f36388-c405-11e5-8fec-1a30293ec564.png)

![image](https://cloud.githubusercontent.com/assets/5666297/12581580/9506a2c0-c405-11e5-9fc0-bdfd67b88bad.png)

In the future, would like to get something a bit more pleasing to the eyes, such as the example below:

![image](https://cloud.githubusercontent.com/assets/5666297/12581606/c933ed3c-c405-11e5-840f-8ea7d2a36515.png)

**Comment by giovanicani** [comment]
not done yet.

**Comment by d3ssupport** [comment]
Tooltip has been removed. Ready to test in UAT

**Comment by giovanicani** [comment]
works. thanks!
