### ISSUE TITLE
Cloud: Add Reason and Position after labour description on the Labour Grid

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#9]
Reduce size of Standard Hours and Quoted Hours to add these 2 extra fields

![image](https://cloud.githubusercontent.com/assets/5666297/11850108/615a1316-a3f9-11e5-876d-b6405d2bacef.png)

**Comment by d3sqa** [comment]
The Reason and Position columns has been added to the Labour's grid at the Edit Quote form. These columns reflects the latest data present against the particular labour. Done at development and will be available at UAT in the next release

![image](https://cloud.githubusercontent.com/assets/13255706/11868983/a29ba940-a4dd-11e5-911c-e4558dd2a0b8.png)

**Comment by giovanicani** [comment]
done. thanks
