### ISSUE TITLE
Cloud: Issues creating Quote from RTMI

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#90]
1. Do not check Trailer or Reefer, leave it to the manager once he opens the Quote
2. Expiry Date needs to be populated with 30 days after the Quote Date.
3. Incorrect TZ, Quote was created at 9:44AM
4. Bill To is empty, should have been populated as well.

![screen shot 2016-01-26 at 9 47 51 am](https://cloud.githubusercontent.com/assets/5666297/12583717/1c930ac4-c412-11e5-82a9-cc3fc514a306.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Above written changes has been done.

For nr001 user, the offset is -7. During the creation of quote, the GMT was 10:29 AM. When conversion happened, the time was converted to 3:29 AM.

Please see screenshot below:

![screenshot_55](https://cloud.githubusercontent.com/assets/13255706/12610992/69a02e14-c50c-11e5-9125-7f1ccf886b96.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
okay!
