### ISSUE TITLE
Cloud: Workflow not working as designed

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#91]
This Quote still needs approval from Reefer Manager, why is it saying that is send to customer pending ?

![image](https://cloud.githubusercontent.com/assets/5666297/12583932/19945f7a-c413-11e5-863d-bfcf4b082645.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Please see screenshots below:

![image](https://cloud.githubusercontent.com/assets/13255706/12612857/8b422936-c517-11e5-8c1e-8db18bab5bd8.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12612902/e1a5aa46-c517-11e5-8be1-8b5ba1117c07.png)

![image](https://cloud.githubusercontent.com/assets/13255706/12612924/fd018b34-c517-11e5-8429-d04918189611.png)

**Comment by giovanicani** [comment]
Good Thanks!
