### ISSUE TITLE
Cloud: Able to enter invalid email content on the email box

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#92]
We spoke about this already, when exiting the field, program should validate email address.

Empty text should read: Email addresses should be separated by , or ;

![image](https://cloud.githubusercontent.com/assets/5666297/12584311/dccf1b00-c414-11e5-8c8d-cca8ff521459.png)

**Comment by d3sqa** [comment]
Whenever the email field is exited, the validation message will be prompted. Ready to test in UAT Environment
Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12612587/9fad71d4-c515-11e5-80e5-5df31b7bdbea.png)

**Comment by giovanicani** [comment]
ok, will test.

**Comment by giovanicani** [comment]
looks good. Thanks!
