### ISSUE TITLE
Cloud and Mobile: Labour Missing on Mobile 

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#93]
See image below:

Created quote, entered 2 labour lines, approved, un approved, SAVED, went into mobile, refreshed the quotes on the inquiry screen, retrieved the Quote and how come there is only one labour line on mobile ?

![image](https://cloud.githubusercontent.com/assets/5666297/12585083/78809fda-c418-11e5-9df7-d7ae7f3d5612.png)

**Comment by giovanicani** [comment]
On this same Quote, Parts added on the mobile were never synched to the Server, even after CLOSE & SAVE operation on Mobile.

When testing this fix, please make sure that:
--
All labour changes, deletion, new images, etc... are properly saved and available on server.
All parts changes, deletion, parts without par_id, are properly saved and available on server.

**Comment by d3ssupport** [comment]
There is one Labour with Active Flag N that why it does't seen on mobile. we will implement this check also on Cloud side.

![image](https://cloud.githubusercontent.com/assets/13255682/12588295/c7d15b22-c479-11e5-8ade-24d7b9e6ba9b.png)

**Comment by giovanicani** [comment]
This needs to be done in the ENTIRE application. Not active records should not be available for selection on the MRO or QUOTE.

**Comment by d3sqa** [comment]
Only active records at Labour and Parts would be displayed at web application. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
ok thanks!
