### ISSUE TITLE
Cloud: Workflow rule issue

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#94]
See below, a quote cannot be approved by a customer before being approved internally (
TRAILER QUOTE REVIEWED INTERNALLY AND APPROVED and / or 
REEFER QUOTE REVIEWED INTERNALLY AND APPROVED)

Only after approved at Trailcon it can be sent to customer and / or approved by customer (2 options of customer approval). 

**Scenario Not allowed**
![image](https://cloud.githubusercontent.com/assets/5666297/12591714/2de4a9b6-c437-11e5-94cd-3ceff3b11aa7.png)

**Scenario Not allowed**
![image](https://cloud.githubusercontent.com/assets/5666297/12591837/c2beb9f0-c437-11e5-9ac5-edc6b92f628a.png)

**Scenario allowed**
![image](https://cloud.githubusercontent.com/assets/5666297/12591887/eaadf822-c437-11e5-9921-aa6b5b8e913c.png)

**Scenario allowed**
![image](https://cloud.githubusercontent.com/assets/5666297/12591911/0940652c-c438-11e5-8e58-03261fe9559a.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
The fields will remain disabled unless one of the 'TRAILER QUOTE REVIEWED INTERNALLY AND APPROVED' or 'REEFER QUOTE REVIEWED INTERNALLY AND APPROVED' gets checked

![image](https://cloud.githubusercontent.com/assets/13255706/12641329/d5692834-c5d0-11e5-9cd4-87d8b00b8dc3.png)

When checked, they will become enabled:

![image](https://cloud.githubusercontent.com/assets/13255706/12641345/e9a307de-c5d0-11e5-8271-857a4550d948.png)

Ready to test in UAT Environment

**Comment by giovanicani** [comment]
Can you please make sure that the Close check box is always available ? Thanks.

**Comment by d3sqa** [comment]
@giovanicani, currently only a few users can click the Close checkbox and can close the quote. The reason why the close checkbox was disabled was that the user does not have the privilege to do so

**Comment by giovanicani** [comment]
okay makes sense.
