### ISSUE TITLE
Mobile: Switch sides - Notes, verbiage adjustment

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#95]
On the Quote Detail screen on the mobile, please move the Dispatch Notes to the LEFT half of the screen, and Notes to the RIGHT side of the screen.

Also on mobile change the label of the field to match the cloud. Change Notes to "Notes (Shown on Customer Reports)"

![image](https://cloud.githubusercontent.com/assets/5666297/12592095/f583cabe-c438-11e5-86f4-a817d229c5ed.png)

**Comment by d3sqa** [comment]
Position of the fields has been changed and the label has been updated. Please see screenshot below:

![image](https://cloud.githubusercontent.com/assets/13255706/12611430/4d1f1bea-c50e-11e5-95c2-fbbd44652588.png)

Fix will be shipped via upcoming application updates

**Comment by giovanicani** [comment]
thanks!
