### ISSUE TITLE
Cloud: Close Notes should also be added to audit log

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#96]
See image below, close notes entered are not showing on audit log. They should also appear here.

![image](https://cloud.githubusercontent.com/assets/5666297/12592271/c07a7f88-c439-11e5-86a0-7d72042b95a5.png)

**Comment by d3sqa** [comment]
Work in progress

**Comment by d3sqa** [comment]
Done. Close Notes are now displayed at audit log. Please check screenshot below:

![screenshot_56](https://cloud.githubusercontent.com/assets/13255706/12612676/60aebf3c-c516-11e5-8135-f15b208c0409.png)

Ready to test in UAT environment

**Comment by giovanicani** [comment]
good. thanks!
