### ISSUE TITLE
Mobile / Cloud: When creating Quote from Mobile, email list not poping up.

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#98]
When creating Quote from Mobile, email box is not being populated with emails from the contact list. See attached screen shot.

***Make sure that email list is also populated when creating from RTMI***

![image](https://cloud.githubusercontent.com/assets/5666297/12592798/fd5bb082-c43b-11e5-94f8-ef55e1bf6e71.png)

**Comment by d3ssupport** [comment]
WORK IN PROGRESS

**Comment by giovanicani** [comment]
Please also make sure that on the Cloud Quote, when unit is entered and customer is auto populated, that the emails also also populated based on the customer.

**Comment by d3sqa** [comment]
The below screenshot shows a Quote created from mobile with Customer 'WAL200'. The message data field is auto-populated with emails:

![image](https://cloud.githubusercontent.com/assets/13255706/12641627/5347423a-c5d2-11e5-8661-f93b7f18e01e.png)

When a unit is changed, along with the customer, email addresses will also auto populate on Quote forms. Ready to test in UAT Environment

**Comment by giovanicani** [comment]
okay, giovani to test.

**Comment by giovanicani** [comment]
okay works.
