### ISSUE TITLE
Cloud / Mobile: When entered unit info, not bringing last return from RTMI

### ISSUE THREAD

**Issue by giovanicani** [GCSO2/D3S-QUOTE#99]
See example below on UAT, this unit has a return date on RTMI RTMI00029500

![image](https://cloud.githubusercontent.com/assets/5666297/12593053/160d3582-c43d-11e5-9c2d-1ffcfd083de6.png)

This RTMI seems to be the last return:
![image](https://cloud.githubusercontent.com/assets/5666297/12593080/3b5323d8-c43d-11e5-9c44-3877321dd920.png)

**Comment by d3sqa** [comment]
@giovanicani, RTMI00029500 is not the last RTMI. Please check screenshots below with their inbound dates:

![new1](https://cloud.githubusercontent.com/assets/13255706/12605643/9b2aece0-c4e8-11e5-9a76-0b328366ed5c.png)

The inbound date for this RTMI is 8th January, 2016. Where as, there is another RTMI against the same unit which would be the last RTMI having date 15th January, 2016.

![new2](https://cloud.githubusercontent.com/assets/13255706/12605668/cec25278-c4e8-11e5-972d-6804debace66.png)

**Comment by giovanicani** [comment]
correct, it was my mistake
